In [1]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA:", torch.version.cuda)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "VRAM:",
        round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2),
        "GB"
    )

PyTorch: 2.5.1+cu121
CUDA available: True
CUDA: 12.1
GPU: NVIDIA GeForce RTX 4080
VRAM: 15.99 GB

In [2]:
from pathlib import Path
import pandas as pd
import numpy as np

# ==============================
# ここだけ実際の場所に変更
# ==============================
NPY_DIR = Path("../OneDrive/ドキュメント/PedAI/pediatric_images_uint8.npy")
CSV_PATH = Path("../OneDrive/ドキュメント/PedAI/pediatric_metadata.csv")

print("NPY dir exists :", NPY_DIR.exists())
print("CSV exists     :", CSV_PATH.exists())

# CSV確認
df = pd.read_csv(CSV_PATH)

print("\n=== Metadata ===")
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

display(df.head())

# NPY確認
npy_files = list(NPY_DIR.rglob("*.npy"))

print("\n=== NPY ===")
print("Number of npy files:", len(npy_files))

if npy_files:
    x = np.load(npy_files[0])
    print("Example:", npy_files[0])
    print("Shape  :", x.shape)
    print("dtype  :", x.dtype)
    print("min/max:", x.min(), x.max())

NPY dir exists : True
CSV exists     : True

=== Metadata ===
Shape: (1085, 8)

Columns:
['patient_id', 'image_name', 'path', 'label', 'age', 'age_group', 'png_path', 'array_idx']

,patient_id,image_name,path,label,age,age_group,png_path,array_idx
0,2450,00002450_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,0,4,age_01_05,/kaggle/input/datasets/khanfashee/nih-chest-x-...,0
1,2555,00002555_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,1,5,age_01_05,/kaggle/input/datasets/khanfashee/nih-chest-x-...,1
2,4028,00004028_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,0,5,age_01_05,/kaggle/input/datasets/khanfashee/nih-chest-x-...,2
3,4535,00004535_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,0,5,age_01_05,/kaggle/input/datasets/khanfashee/nih-chest-x-...,3
4,4987,00004987_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,1,4,age_01_05,/kaggle/input/datasets/khanfashee/nih-chest-x-...,4

=== NPY ===
Number of npy files: 0

In [3]:
from pathlib import Path
import numpy as np
import pandas as pd

NPY_PATH = Path(
    "../OneDrive/ドキュメント/PedAI/pediatric_images_uint8.npy"
)

print("Exists:", NPY_PATH.exists())
print("File:", NPY_PATH.resolve())
print(f"Size: {NPY_PATH.stat().st_size / 1024**3:.2f} GB")

X = np.load(NPY_PATH, mmap_mode="r")

print("\n=== NPY ===")
print("shape :", X.shape)
print("dtype :", X.dtype)
print("min   :", X.min())
print("max   :", X.max())

Exists: True
File: /mnt/c/Users/yoshi/OneDrive/ドキュメント/PedAI/pediatric_images_uint8.npy
Size: 0.05 GB

=== NPY ===
shape : (1085, 224, 224)
dtype : uint8
min   : 0
max   : 255

In [7]:
!pip install -U optuna
!pip uninstall -y pediatric-resnet-finetuning
!pip install --no-cache-dir --force-reinstall --no-deps \
"git+https://github.com/YoshifumiMiyagi/pediatric-resnet-finetuning.git"

Requirement already satisfied: optuna in /home/yoshi/miniconda3/envs/evo2/lib/python3.11/site-packages (5.0.0)
Requirement already satisfied: alembic>=1.5.0 in /home/yoshi/miniconda3/envs/evo2/lib/python3.11/site-packages (from optuna) (1.20.0)
Requirement already satisfied: colorlog in /home/yoshi/miniconda3/envs/evo2/lib/python3.11/site-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in /home/yoshi/miniconda3/envs/evo2/lib/python3.11/site-packages (from optuna) (2.4.4)
Requirement already satisfied: packaging>=20.0 in /home/yoshi/miniconda3/envs/evo2/lib/python3.11/site-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /home/yoshi/miniconda3/envs/evo2/lib/python3.11/site-packages (from optuna) (2.1.1)
Requirement already satisfied: tqdm in /home/yoshi/miniconda3/envs/evo2/lib/python3.11/site-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /home/yoshi/miniconda3/envs/evo2/lib/python3.11/site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /home/yoshi/miniconda3/envs/evo2/lib/python3.11/site-packages (from alembic>=1.5.0->optuna) (1.4.3)
Requirement already satisfied: typing-extensions>=4.12 in /home/yoshi/miniconda3/envs/evo2/lib/python3.11/site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/yoshi/miniconda3/envs/evo2/lib/python3.11/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
WARNING: Skipping pediatric-resnet-finetuning as it is not installed.
Collecting git+https://github.com/YoshifumiMiyagi/pediatric-resnet-finetuning.git
  Cloning https://github.com/YoshifumiMiyagi/pediatric-resnet-finetuning.git to /tmp/pip-req-build-for4f750
  Running command git clone --filter=blob:none --quiet https://github.com/YoshifumiMiyagi/pediatric-resnet-finetuning.git /tmp/pip-req-build-for4f750
  Resolved https://github.com/YoshifumiMiyagi/pediatric-resnet-finetuning.git to commit f31e7f801a10ca3e9a2e44adee4d63d4c81b381b
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pediatric-resnet-ft
  Building wheel for pediatric-resnet-ft (pyproject.toml) ... done
  Created wheel for pediatric-resnet-ft: filename=pediatric_resnet_ft-0.1.3-py3-none-any.whl size=26853 sha256=3e05b70b645c1e01b841cc88337c4701fc48e73df270ab9ebccd5595b1aa18ac
  Stored in directory: /tmp/pip-ephem-wheel-cache-g6q05syr/wheels/c6/aa/de/aa0f1d5e6df541a09367bf72256f4ef2d3307caf333176e52c
Successfully built pediatric-resnet-ft
Installing collected packages: pediatric-resnet-ft
  Attempting uninstall: pediatric-resnet-ft
    Found existing installation: pediatric-resnet-ft 0.1.3
    Uninstalling pediatric-resnet-ft-0.1.3:
      Successfully uninstalled pediatric-resnet-ft-0.1.3
Successfully installed pediatric-resnet-ft-0.1.3

In [8]:
from pediatric_resnet_ft_NestedCV_inner_optuna.nested_cv_optuna_npy import (
    run_nested_cv
)

import inspect
print(inspect.signature(run_nested_cv))

(csv_path, npy_path, array_idx_col='array_idx', **kwargs)

In [16]:
from pathlib import Path

BASE = Path(
    "/mnt/c/Users/yoshi/OneDrive/ドキュメント/PedAI"
)

NPY_PATH = BASE / "pediatric_images_uint8.npy"

# ↓実際のmetadata CSV名に変更
CSV_PATH = BASE / "pediatric_metadata.csv"

# ↓実際の成人モデル名に変更
ADULT_MODEL = BASE / "resnet50_pa_adult_agefixed_morimoto_20260923_weights.pt"

print("NPY   :", NPY_PATH.exists(), NPY_PATH)
print("CSV   :", CSV_PATH.exists(), CSV_PATH)
print("MODEL :", ADULT_MODEL.exists(), ADULT_MODEL)

NPY   : True /mnt/c/Users/yoshi/OneDrive/ドキュメント/PedAI/pediatric_images_uint8.npy
CSV   : True /mnt/c/Users/yoshi/OneDrive/ドキュメント/PedAI/pediatric_metadata.csv
MODEL : True /mnt/c/Users/yoshi/OneDrive/ドキュメント/PedAI/resnet50_pa_adult_agefixed_morimoto_20260923_weights.pt

In [18]:
import warnings
import optuna

# Optuna: trialごとの[I ...]を非表示
optuna.logging.set_verbosity(optuna.logging.WARNING)

# torch.loadのFutureWarningを非表示
warnings.filterwarnings(
    "ignore",
    category=FutureWarning,
    message=".*torch.load.*weights_only=False.*"
)

In [20]:
import pandas as pd

df = pd.read_csv(CSV_PATH)

summary = (
    df.groupby("age_group")
      .agg(
          images=("label", "size"),
          patients=("patient_id", "nunique"),
          female=("label", "sum"),
      )
)

summary["male"] = summary["images"] - summary["female"]

display(summary)

           images  patients  female  male
age_group
age_01_05     116       103      59    57
age_06_11     404       296     219   185
age_12_17     565       408     319   246

In [22]:
from pathlib import Path
import pandas as pd

df = pd.read_csv(CSV_PATH)

AGE_GROUP = "age_01_05"

df_age = (
    df[df["age_group"] == AGE_GROUP]
    .copy()
    .reset_index(drop=True)
)

print("Age group :", AGE_GROUP)
print("Images    :", len(df_age))
print("Patients  :", df_age["patient_id"].nunique())
print("\nLabels:")
print(df_age["label"].value_counts().sort_index())

# patient内でlabelが一致することを確認
assert (
    df_age.groupby("patient_id")["label"].nunique() == 1
).all()

# 元NPYのindexを保持していることを確認
assert df_age["array_idx"].notna().all()
assert df_age["array_idx"].is_unique

OUT_DIR = Path(
    "/home/yoshi/pediatric_cxr/results/main_nested_by_age/age_01_05"
)
OUT_DIR.mkdir(parents=True, exist_ok=True)

AGE_CSV = OUT_DIR / "metadata_age_01_05.csv"
df_age.to_csv(AGE_CSV, index=False)

print("\nSaved metadata:", AGE_CSV)
print("array_idx range:",
      df_age["array_idx"].min(),
      "->",
      df_age["array_idx"].max())

Age group : age_01_05
Images    : 116
Patients  : 103

Labels:
label
0    57
1    59
Name: count, dtype: int64

Saved metadata: /home/yoshi/pediatric_cxr/results/main_nested_by_age/age_01_05/metadata_age_01_05.csv
array_idx range: 0 -> 115

In [23]:
from pediatric_resnet_ft_NestedCV_inner_optuna.nested_cv_optuna_npy import (
    run_nested_cv
)

start_time = time.time()

results_01_05 = run_nested_cv(
    csv_path=str(AGE_CSV),
    npy_path=str(NPY_PATH),
    array_idx_col="array_idx",

    # Adult pretrained model
    pretrained="adult",
    pretrained_path=str(ADULT_MODEL),

    # Fine-tuning
    mode="layer4",

    # Columns
    label_col="label",
    id_col="patient_id",
    group_col="patient_id",

    # ====================================
    # Nested CV
    # ====================================
    outer_splits=5,
    inner_splits=5,
    n_trials=20,

    # ====================================
    # GPU
    # ====================================
    batch_size=32,
    num_workers=4,
    device="cuda",

    # ====================================
    # Optuna search space
    # ====================================
    optimizer_choices=(
        "AdamW",
        "Adam",
        "SGD",
    ),

    loss_choices=(
        "bce",
        "bce_label_smoothing",
        "focal",
    ),

    lr_range=(1e-5, 5e-4),
    sgd_lr_range=(1e-4, 1e-2),
    weight_decay_range=(1e-6, 1e-3),

    epoch_range=(5, 30),

    # ====================================
    # Reproducibility / output
    # ====================================
    seed=42,

    output_dir=str(OUT_DIR),

    verbose=True,
)

elapsed = time.time() - start_time

print("\n" + "=" * 70)
print("AGE 1–5 MAIN ANALYSIS FINISHED")
print("=" * 70)

print("End      :", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print(f"Time     : {elapsed / 60:.1f} min")
print(f"Time     : {elapsed / 3600:.2f} hours")
print(f"OOF AUC  : {results_01_05['oof_auc']:.4f}")

NPY backend: /mnt/c/Users/yoshi/OneDrive/ドキュメント/PedAI/pediatric_images_uint8.npy
NPY shape=(1085, 224, 224), dtype=uint8, index_col=array_idx
Nested CV outer=5 inner=5 trials=20
Outer 1/5: train=93 test=23
best=0.6570, optimizer=Adam, loss=bce_label_smoothing, epochs=14, test AUC=0.6136
Outer 2/5: train=92 test=24
best=0.6170, optimizer=SGD, loss=focal, epochs=7, test AUC=0.7361
Outer 3/5: train=93 test=23

IOStream.flush timed out

best=0.6620, optimizer=Adam, loss=focal, epochs=18, test AUC=0.6212
Outer 4/5: train=93 test=23
best=0.6494, optimizer=AdamW, loss=bce_label_smoothing, epochs=9, test AUC=0.5985
Outer 5/5: train=93 test=23

IOStream.flush timed out
IOStream.flush timed out

best=0.6565, optimizer=SGD, loss=bce_label_smoothing, epochs=18, test AUC=0.4924
Nested-CV image-level OOF AUC=0.5935; Saved: /home/yoshi/pediatric_cxr/results/main_nested_by_age/age_01_05

======================================================================
AGE 1–5 MAIN ANALYSIS FINISHED
======================================================================
End      : 2026-09-30 21:37:53
Time     : 41.2 min
Time     : 0.69 hours
OOF AUC  : 0.5935

In [24]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

# ============================================================
# Settings
# ============================================================

N_BOOT = 2000
BOOT_SEED = 12345

# Nested CV OOF
oof = results_01_05["oof"].copy()

print("OOF shape:", oof.shape)
print("Columns:", oof.columns.tolist())

# ============================================================
# 1. Safety checks
# ============================================================

required = ["patient_id", "label", "oof_prob"]

missing = [c for c in required if c not in oof.columns]
if missing:
    raise ValueError(f"Missing columns: {missing}")

# 同一patient内でlabelが一致していることを確認
label_check = oof.groupby("patient_id")["label"].nunique()

assert (label_check == 1).all(), \
    "Same patient has inconsistent labels."

# OOF predictionに欠損がない
assert oof["oof_prob"].notna().all()

print("\nImages   :", len(oof))
print("Patients :", oof["patient_id"].nunique())


# ============================================================
# 2. Aggregate image predictions to patient level
#
# Multiple images / patient:
# mean OOF probability
# ============================================================

patient_oof = (
    oof
    .groupby("patient_id", as_index=False)
    .agg(
        label=("label", "first"),
        oof_prob=("oof_prob", "mean"),
        n_images=("oof_prob", "size"),
    )
)

print("\n=== Patient-level OOF ===")
print("Patients:", len(patient_oof))
print("\nLabels:")
print(patient_oof["label"].value_counts().sort_index())

print("\nImages per patient:")
print(patient_oof["n_images"].describe())


# ============================================================
# 3. Patient-level OOF AUC
# ============================================================

y_true = patient_oof["label"].to_numpy()
y_prob = patient_oof["oof_prob"].to_numpy()

patient_auc = roc_auc_score(y_true, y_prob)

print("\nPatient-level OOF AUC:")
print(f"{patient_auc:.4f}")


# ============================================================
# 4. Patient-level bootstrap 95% CI
#
# Resampling unit = patient
# ============================================================

rng = np.random.default_rng(BOOT_SEED)

n = len(patient_oof)

boot_auc = []

for _ in range(N_BOOT):

    # patient単位で復元抽出
    idx = rng.integers(
        low=0,
        high=n,
        size=n
    )

    y_b = y_true[idx]
    p_b = y_prob[idx]

    # bootstrap sampleに片方のclassしかない場合はskip
    if np.unique(y_b).size < 2:
        continue

    boot_auc.append(
        roc_auc_score(y_b, p_b)
    )

boot_auc = np.asarray(boot_auc)

ci_low, ci_high = np.percentile(
    boot_auc,
    [2.5, 97.5]
)


# ============================================================
# 5. Results
# ============================================================

print("\n" + "=" * 60)
print("PATIENT-LEVEL NESTED-CV PERFORMANCE")
print("=" * 60)

print(f"N patients     : {n}")
print(f"OOF AUC        : {patient_auc:.4f}")
print(
    f"95% bootstrap CI: "
    f"{ci_low:.4f} – {ci_high:.4f}"
)
print(f"Bootstrap reps : {len(boot_auc)}")


# ============================================================
# 6. Save
# ============================================================

patient_oof.to_csv(
    OUT_DIR / "patient_level_oof_predictions.csv",
    index=False
)

summary = pd.DataFrame({
    "age_group": ["age_01_05"],
    "n_images": [len(oof)],
    "n_patients": [n],
    "patient_oof_auc": [patient_auc],
    "ci_low": [ci_low],
    "ci_high": [ci_high],
    "n_boot": [len(boot_auc)],
})

summary.to_csv(
    OUT_DIR / "patient_level_auc_summary.csv",
    index=False
)

display(summary)

OOF shape: (116, 5)
Columns: ['patient_id', 'array_idx', 'label', 'outer_fold', 'oof_prob']

Images   : 116
Patients : 103

=== Patient-level OOF ===
Patients: 103

Labels:
label
0    49
1    54
Name: count, dtype: int64

Images per patient:
count    103.000000
mean       1.126214
std        0.388047
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        3.000000
Name: n_images, dtype: float64

Patient-level OOF AUC:
0.5952

============================================================
PATIENT-LEVEL NESTED-CV PERFORMANCE
============================================================
N patients     : 103
OOF AUC        : 0.5952
95% bootstrap CI: 0.4781 – 0.7057
Bootstrap reps : 2000

,age_group,n_images,n_patients,patient_oof_auc,ci_low,ci_high,n_boot
0,age_01_05,116,103,0.595238,0.478102,0.705712,2000

# 6-11歳

In [25]:
from pathlib import Path
import pandas as pd

df = pd.read_csv(CSV_PATH)

AGE_GROUP = "age_06_11"

df_age = (
    df[df["age_group"] == AGE_GROUP]
    .copy()
    .reset_index(drop=True)
)

print("Age group :", AGE_GROUP)
print("Images    :", len(df_age))
print("Patients  :", df_age["patient_id"].nunique())
print("\nLabels:")
print(df_age["label"].value_counts().sort_index())

# patient内でlabelが一致することを確認
assert (
    df_age.groupby("patient_id")["label"].nunique() == 1
).all()

# 元NPYのindexを保持していることを確認
assert df_age["array_idx"].notna().all()
assert df_age["array_idx"].is_unique

OUT_DIR = Path(
    "/home/yoshi/pediatric_cxr/results/main_nested_by_age/age_06_11"
)
OUT_DIR.mkdir(parents=True, exist_ok=True)

AGE_CSV = OUT_DIR / "metadata_age_06_11.csv"
df_age.to_csv(AGE_CSV, index=False)

print("\nSaved metadata:", AGE_CSV)
print("array_idx range:",
      df_age["array_idx"].min(),
      "->",
      df_age["array_idx"].max())

Age group : age_06_11
Images    : 404
Patients  : 296

Labels:
label
0    185
1    219
Name: count, dtype: int64

Saved metadata: /home/yoshi/pediatric_cxr/results/main_nested_by_age/age_06_11/metadata_age_06_11.csv
array_idx range: 116 -> 519

In [26]:
from pediatric_resnet_ft_NestedCV_inner_optuna.nested_cv_optuna_npy import (
    run_nested_cv
)

start_time = time.time()

results_06_11 = run_nested_cv(
    csv_path=str(AGE_CSV),
    npy_path=str(NPY_PATH),
    array_idx_col="array_idx",

    # Adult pretrained model
    pretrained="adult",
    pretrained_path=str(ADULT_MODEL),

    # Fine-tuning
    mode="layer4",

    # Columns
    label_col="label",
    id_col="patient_id",
    group_col="patient_id",

    # ====================================
    # Nested CV
    # ====================================
    outer_splits=5,
    inner_splits=5,
    n_trials=20,

    # ====================================
    # GPU
    # ====================================
    batch_size=32,
    num_workers=4,
    device="cuda",

    # ====================================
    # Optuna search space
    # ====================================
    optimizer_choices=(
        "AdamW",
        "Adam",
        "SGD",
    ),

    loss_choices=(
        "bce",
        "bce_label_smoothing",
        "focal",
    ),

    lr_range=(1e-5, 5e-4),
    sgd_lr_range=(1e-4, 1e-2),
    weight_decay_range=(1e-6, 1e-3),

    epoch_range=(5, 30),

    # ====================================
    # Reproducibility / output
    # ====================================
    seed=42,

    output_dir=str(OUT_DIR),

    verbose=True,
)

elapsed = time.time() - start_time

print("\n" + "=" * 70)
print("AGE 6–11 MAIN ANALYSIS FINISHED")
print("=" * 70)

print("End      :", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print(f"Time     : {elapsed / 60:.1f} min")
print(f"Time     : {elapsed / 3600:.2f} hours")
print(f"OOF AUC  : {results_06_11['oof_auc']:.4f}")

NPY backend: /mnt/c/Users/yoshi/OneDrive/ドキュメント/PedAI/pediatric_images_uint8.npy
NPY shape=(1085, 224, 224), dtype=uint8, index_col=array_idx
Nested CV outer=5 inner=5 trials=20
Outer 1/5: train=323 test=81

IOStream.flush timed out
IOStream.flush timed out

best=0.7429, optimizer=Adam, loss=bce, epochs=11, test AUC=0.7082
Outer 2/5: train=323 test=81
best=0.7400, optimizer=SGD, loss=bce_label_smoothing, epochs=30, test AUC=0.7273
Outer 3/5: train=323 test=81
best=0.7201, optimizer=Adam, loss=focal, epochs=24, test AUC=0.7039
Outer 4/5: train=324 test=80
best=0.7581, optimizer=AdamW, loss=bce_label_smoothing, epochs=7, test AUC=0.7304
Outer 5/5: train=323 test=81

IOStream.flush timed out

best=0.7533, optimizer=SGD, loss=bce, epochs=29, test AUC=0.6505
Nested-CV image-level OOF AUC=0.6869; Saved: /home/yoshi/pediatric_cxr/results/main_nested_by_age/age_06_11

======================================================================
AGE 6–11 MAIN ANALYSIS FINISHED
======================================================================
End      : 2026-09-30 23:03:51
Time     : 78.3 min
Time     : 1.30 hours
OOF AUC  : 0.6869

In [27]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

# ============================================================
# Settings
# ============================================================

N_BOOT = 2000
BOOT_SEED = 12345

# Nested CV OOF
oof = results_06_11["oof"].copy()

print("OOF shape:", oof.shape)
print("Columns:", oof.columns.tolist())

# ============================================================
# 1. Safety checks
# ============================================================

required = ["patient_id", "label", "oof_prob"]

missing = [c for c in required if c not in oof.columns]
if missing:
    raise ValueError(f"Missing columns: {missing}")

# 同一patient内でlabelが一致していることを確認
label_check = oof.groupby("patient_id")["label"].nunique()

assert (label_check == 1).all(), \
    "Same patient has inconsistent labels."

# OOF predictionに欠損がない
assert oof["oof_prob"].notna().all()

print("\nImages   :", len(oof))
print("Patients :", oof["patient_id"].nunique())


# ============================================================
# 2. Aggregate image predictions to patient level
#
# Multiple images / patient:
# mean OOF probability
# ============================================================

patient_oof = (
    oof
    .groupby("patient_id", as_index=False)
    .agg(
        label=("label", "first"),
        oof_prob=("oof_prob", "mean"),
        n_images=("oof_prob", "size"),
    )
)

print("\n=== Patient-level OOF ===")
print("Patients:", len(patient_oof))
print("\nLabels:")
print(patient_oof["label"].value_counts().sort_index())

print("\nImages per patient:")
print(patient_oof["n_images"].describe())


# ============================================================
# 3. Patient-level OOF AUC
# ============================================================

y_true = patient_oof["label"].to_numpy()
y_prob = patient_oof["oof_prob"].to_numpy()

patient_auc = roc_auc_score(y_true, y_prob)

print("\nPatient-level OOF AUC:")
print(f"{patient_auc:.4f}")


# ============================================================
# 4. Patient-level bootstrap 95% CI
#
# Resampling unit = patient
# ============================================================

rng = np.random.default_rng(BOOT_SEED)

n = len(patient_oof)

boot_auc = []

for _ in range(N_BOOT):

    # patient単位で復元抽出
    idx = rng.integers(
        low=0,
        high=n,
        size=n
    )

    y_b = y_true[idx]
    p_b = y_prob[idx]

    # bootstrap sampleに片方のclassしかない場合はskip
    if np.unique(y_b).size < 2:
        continue

    boot_auc.append(
        roc_auc_score(y_b, p_b)
    )

boot_auc = np.asarray(boot_auc)

ci_low, ci_high = np.percentile(
    boot_auc,
    [2.5, 97.5]
)


# ============================================================
# 5. Results
# ============================================================

print("\n" + "=" * 60)
print("PATIENT-LEVEL NESTED-CV PERFORMANCE")
print("=" * 60)

print(f"N patients     : {n}")
print(f"OOF AUC        : {patient_auc:.4f}")
print(
    f"95% bootstrap CI: "
    f"{ci_low:.4f} – {ci_high:.4f}"
)
print(f"Bootstrap reps : {len(boot_auc)}")


# ============================================================
# 6. Save
# ============================================================

patient_oof.to_csv(
    OUT_DIR / "patient_level_oof_predictions_6_11.csv",
    index=False
)

summary = pd.DataFrame({
    "age_group": ["age_06_11"],
    "n_images": [len(oof)],
    "n_patients": [n],
    "patient_oof_auc": [patient_auc],
    "ci_low": [ci_low],
    "ci_high": [ci_high],
    "n_boot": [len(boot_auc)],
})

summary.to_csv(
    OUT_DIR / "patient_level_auc_summary_6_11.csv",
    index=False
)

display(summary)

OOF shape: (404, 5)
Columns: ['patient_id', 'array_idx', 'label', 'outer_fold', 'oof_prob']

Images   : 404
Patients : 296

=== Patient-level OOF ===
Patients: 296

Labels:
label
0    135
1    161
Name: count, dtype: int64

Images per patient:
count    296.000000
mean       1.364865
std        0.832791
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        7.000000
Name: n_images, dtype: float64

Patient-level OOF AUC:
0.6882

============================================================
PATIENT-LEVEL NESTED-CV PERFORMANCE
============================================================
N patients     : 296
OOF AUC        : 0.6882
95% bootstrap CI: 0.6275 – 0.7484
Bootstrap reps : 2000

,age_group,n_images,n_patients,patient_oof_auc,ci_low,ci_high,n_boot
0,age_06_11,404,296,0.688153,0.627462,0.748398,2000

# 12-17歳

In [28]:
from pathlib import Path
import pandas as pd

df = pd.read_csv(CSV_PATH)

AGE_GROUP = "age_12_17"

df_age = (
    df[df["age_group"] == AGE_GROUP]
    .copy()
    .reset_index(drop=True)
)

print("Age group :", AGE_GROUP)
print("Images    :", len(df_age))
print("Patients  :", df_age["patient_id"].nunique())
print("\nLabels:")
print(df_age["label"].value_counts().sort_index())

# patient内でlabelが一致することを確認
assert (
    df_age.groupby("patient_id")["label"].nunique() == 1
).all()

# 元NPYのindexを保持していることを確認
assert df_age["array_idx"].notna().all()
assert df_age["array_idx"].is_unique

OUT_DIR = Path(
    "/home/yoshi/pediatric_cxr/results/main_nested_by_age/age_12_17"
)
OUT_DIR.mkdir(parents=True, exist_ok=True)

AGE_CSV = OUT_DIR / "metadata_age_12_17.csv"
df_age.to_csv(AGE_CSV, index=False)

print("\nSaved metadata:", AGE_CSV)
print("array_idx range:",
      df_age["array_idx"].min(),
      "->",
      df_age["array_idx"].max())

Age group : age_12_17
Images    : 565
Patients  : 408

Labels:
label
0    246
1    319
Name: count, dtype: int64

Saved metadata: /home/yoshi/pediatric_cxr/results/main_nested_by_age/age_12_17/metadata_age_12_17.csv
array_idx range: 520 -> 1084

In [29]:
from pediatric_resnet_ft_NestedCV_inner_optuna.nested_cv_optuna_npy import (
    run_nested_cv
)

start_time = time.time()

results_12_17 = run_nested_cv(
    csv_path=str(AGE_CSV),
    npy_path=str(NPY_PATH),
    array_idx_col="array_idx",

    # Adult pretrained model
    pretrained="adult",
    pretrained_path=str(ADULT_MODEL),

    # Fine-tuning
    mode="layer4",

    # Columns
    label_col="label",
    id_col="patient_id",
    group_col="patient_id",

    # ====================================
    # Nested CV
    # ====================================
    outer_splits=5,
    inner_splits=5,
    n_trials=20,

    # ====================================
    # GPU
    # ====================================
    batch_size=32,
    num_workers=4,
    device="cuda",

    # ====================================
    # Optuna search space
    # ====================================
    optimizer_choices=(
        "AdamW",
        "Adam",
        "SGD",
    ),

    loss_choices=(
        "bce",
        "bce_label_smoothing",
        "focal",
    ),

    lr_range=(1e-5, 5e-4),
    sgd_lr_range=(1e-4, 1e-2),
    weight_decay_range=(1e-6, 1e-3),

    epoch_range=(5, 30),

    # ====================================
    # Reproducibility / output
    # ====================================
    seed=42,

    output_dir=str(OUT_DIR),

    verbose=True,
)

elapsed = time.time() - start_time

print("\n" + "=" * 70)
print("AGE 12–17 MAIN ANALYSIS FINISHED")
print("=" * 70)

print("End      :", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print(f"Time     : {elapsed / 60:.1f} min")
print(f"Time     : {elapsed / 3600:.2f} hours")
print(f"OOF AUC  : {results_12_17['oof_auc']:.4f}")

NPY backend: /mnt/c/Users/yoshi/OneDrive/ドキュメント/PedAI/pediatric_images_uint8.npy
NPY shape=(1085, 224, 224), dtype=uint8, index_col=array_idx
Nested CV outer=5 inner=5 trials=20
Outer 1/5: train=452 test=113
best=0.9769, optimizer=Adam, loss=focal, epochs=30, test AUC=0.9879
Outer 2/5: train=452 test=113
best=0.9769, optimizer=SGD, loss=bce_label_smoothing, epochs=28, test AUC=0.9688
Outer 3/5: train=452 test=113

IOStream.flush timed out
IOStream.flush timed out
IOStream.flush timed out

best=0.9802, optimizer=SGD, loss=bce_label_smoothing, epochs=23, test AUC=0.9657
Outer 4/5: train=452 test=113

IOStream.flush timed out
IOStream.flush timed out
IOStream.flush timed out
IOStream.flush timed out

best=0.9766, optimizer=AdamW, loss=bce, epochs=5, test AUC=0.9745
Outer 5/5: train=452 test=113
best=0.9731, optimizer=SGD, loss=bce_label_smoothing, epochs=20, test AUC=0.9841
Nested-CV image-level OOF AUC=0.9729; Saved: /home/yoshi/pediatric_cxr/results/main_nested_by_age/age_12_17

======================================================================
AGE 12–17 MAIN ANALYSIS FINISHED
======================================================================
End      : 2026-10-01 00:40:14
Time     : 96.4 min
Time     : 1.61 hours
OOF AUC  : 0.9729

In [30]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

# ============================================================
# Settings
# ============================================================

N_BOOT = 2000
BOOT_SEED = 12345

# Nested CV OOF
oof = results_12_17["oof"].copy()

print("OOF shape:", oof.shape)
print("Columns:", oof.columns.tolist())

# ============================================================
# 1. Safety checks
# ============================================================

required = ["patient_id", "label", "oof_prob"]

missing = [c for c in required if c not in oof.columns]
if missing:
    raise ValueError(f"Missing columns: {missing}")

# 同一patient内でlabelが一致していることを確認
label_check = oof.groupby("patient_id")["label"].nunique()

assert (label_check == 1).all(), \
    "Same patient has inconsistent labels."

# OOF predictionに欠損がない
assert oof["oof_prob"].notna().all()

print("\nImages   :", len(oof))
print("Patients :", oof["patient_id"].nunique())


# ============================================================
# 2. Aggregate image predictions to patient level
#
# Multiple images / patient:
# mean OOF probability
# ============================================================

patient_oof = (
    oof
    .groupby("patient_id", as_index=False)
    .agg(
        label=("label", "first"),
        oof_prob=("oof_prob", "mean"),
        n_images=("oof_prob", "size"),
    )
)

print("\n=== Patient-level OOF ===")
print("Patients:", len(patient_oof))
print("\nLabels:")
print(patient_oof["label"].value_counts().sort_index())

print("\nImages per patient:")
print(patient_oof["n_images"].describe())


# ============================================================
# 3. Patient-level OOF AUC
# ============================================================

y_true = patient_oof["label"].to_numpy()
y_prob = patient_oof["oof_prob"].to_numpy()

patient_auc = roc_auc_score(y_true, y_prob)

print("\nPatient-level OOF AUC:")
print(f"{patient_auc:.4f}")


# ============================================================
# 4. Patient-level bootstrap 95% CI
#
# Resampling unit = patient
# ============================================================

rng = np.random.default_rng(BOOT_SEED)

n = len(patient_oof)

boot_auc = []

for _ in range(N_BOOT):

    # patient単位で復元抽出
    idx = rng.integers(
        low=0,
        high=n,
        size=n
    )

    y_b = y_true[idx]
    p_b = y_prob[idx]

    # bootstrap sampleに片方のclassしかない場合はskip
    if np.unique(y_b).size < 2:
        continue

    boot_auc.append(
        roc_auc_score(y_b, p_b)
    )

boot_auc = np.asarray(boot_auc)

ci_low, ci_high = np.percentile(
    boot_auc,
    [2.5, 97.5]
)


# ============================================================
# 5. Results
# ============================================================

print("\n" + "=" * 60)
print("PATIENT-LEVEL NESTED-CV PERFORMANCE")
print("=" * 60)

print(f"N patients     : {n}")
print(f"OOF AUC        : {patient_auc:.4f}")
print(
    f"95% bootstrap CI: "
    f"{ci_low:.4f} – {ci_high:.4f}"
)
print(f"Bootstrap reps : {len(boot_auc)}")


# ============================================================
# 6. Save
# ============================================================

patient_oof.to_csv(
    OUT_DIR / "patient_level_oof_predictions_12_17.csv",
    index=False
)

summary = pd.DataFrame({
    "age_group": ["age_12_17"],
    "n_images": [len(oof)],
    "n_patients": [n],
    "patient_oof_auc": [patient_auc],
    "ci_low": [ci_low],
    "ci_high": [ci_high],
    "n_boot": [len(boot_auc)],
})

summary.to_csv(
    OUT_DIR / "patient_level_auc_summary_12_17.csv",
    index=False
)

display(summary)

OOF shape: (565, 5)
Columns: ['patient_id', 'array_idx', 'label', 'outer_fold', 'oof_prob']

Images   : 565
Patients : 408

=== Patient-level OOF ===
Patients: 408

Labels:
label
0    169
1    239
Name: count, dtype: int64

Images per patient:
count    408.000000
mean       1.384804
std        0.901249
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        7.000000
Name: n_images, dtype: float64

Patient-level OOF AUC:
0.9749

============================================================
PATIENT-LEVEL NESTED-CV PERFORMANCE
============================================================
N patients     : 408
OOF AUC        : 0.9749
95% bootstrap CI: 0.9612 – 0.9851
Bootstrap reps : 2000

,age_group,n_images,n_patients,patient_oof_auc,ci_low,ci_high,n_boot
0,age_12_17,565,408,0.974871,0.961154,0.985139,2000