In [11]:
!pip install git+https://github.com/YoshifumiMiyagi/pediatric-resnet-finetuning.git

Collecting git+https://github.com/YoshifumiMiyagi/pediatric-resnet-finetuning.git
  Cloning https://github.com/YoshifumiMiyagi/pediatric-resnet-finetuning.git to /tmp/pip-req-build-_9ygzxat
  Running command git clone --filter=blob:none --quiet https://github.com/YoshifumiMiyagi/pediatric-resnet-finetuning.git /tmp/pip-req-build-_9ygzxat
  Resolved https://github.com/YoshifumiMiyagi/pediatric-resnet-finetuning.git to commit 4d5373af6d42b6dffdc3b5dcd23423f22a2c3dc4
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: torch>=2.0 in /usr/local/lib/python3.13/dist-packages (from pediatric-resnet-ft==0.1.3) (2.11.0+cu128)
Requirement already satisfied: torchvision>=0.15 in /usr/local/lib/python3.13/dist-packages (from pediatric-resnet-ft==0.1.3) (0.26.0+cu128)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.13/dist-packages (from pediatric-resnet-ft==0.1.3) (2.1.3)
Requirement already satisfied: pandas>=1.5 in /usr/local/lib/python3.13/dist-packages (from pediatric-resnet-ft==0.1.3) (2.2.3)
Requirement already satisfied: scikit-learn>=1.2 in /usr/local/lib/python3.13/dist-packages (from pediatric-resnet-ft==0.1.3) (1.6.1)
Requirement already satisfied: Pillow>=9.0 in /usr/local/lib/python3.13/dist-packages (from pediatric-resnet-ft==0.1.3) (11.3.0)
Requirement already satisfied: openpyxl>=3.1 in /usr/local/lib/python3.13/dist-packages (from pediatric-resnet-ft==0.1.3) (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl>=3.1->pediatric-resnet-ft==0.1.3) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.5->pediatric-resnet-ft==0.1.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.5->pediatric-resnet-ft==0.1.3) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.5->pediatric-resnet-ft==0.1.3) (2026.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.2->pediatric-resnet-ft==0.1.3) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.2->pediatric-resnet-ft==0.1.3) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.2->pediatric-resnet-ft==0.1.3) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->pediatric-resnet-ft==0.1.3) (3.32.5)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->pediatric-resnet-ft==0.1.3) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->pediatric-resnet-ft==0.1.3) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->pediatric-resnet-ft==0.1.3) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->pediatric-resnet-ft==0.1.3) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->pediatric-resnet-ft==0.1.3) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->pediatric-resnet-ft==0.1.3) (2025.12.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0->pediatric-resnet-ft==0.1.3) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->pediatric-resnet-ft==0.1.3) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->pediatric-resnet-ft==0.1.3) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->pediatric-resnet-ft==0.1.3) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->pediatric-resnet-ft==0.1.3) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->pediatric-resnet-ft==0.1.3) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->pediatric-resnet-ft==0.1.3) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0->pediatric-resnet-ft==0.1.3) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0->pediatric-resnet-ft==0.1.3) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0->pediatric-resnet-ft==0.1.3) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0->pediatric-resnet-ft==0.1.3) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0->pediatric-resnet-ft==0.1.3) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0->pediatric-resnet-ft==0.1.3) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0->pediatric-resnet-ft==0.1.3) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0->pediatric-resnet-ft==0.1.3) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0->pediatric-resnet-ft==0.1.3) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0->pediatric-resnet-ft==0.1.3) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0->pediatric-resnet-ft==0.1.3) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0->pediatric-resnet-ft==0.1.3) (1.8.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=1.2->pediatric-resnet-ft==0.1.3) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.5->pediatric-resnet-ft==0.1.3) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.0->pediatric-resnet-ft==0.1.3) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.0->pediatric-resnet-ft==0.1.3) (3.0.3)

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# 0-5歳 partial Fine-tuning (Layer4)

In [13]:
from pediatric_resnet_ft import build_dataset_csv

df_young = build_dataset_csv(
    metadata_path="/content/drive/MyDrive/PedAI_ChestXp/For_finetuning/QC/merged_reviewer_results_260906.xlsx",
    image_dir="/content/drive/MyDrive/PedAI_ChestXp/For_finetuning/QC/age_01_05",
    output_csv="/content/drive/MyDrive/QC/age_01_05.csv",
)

print(df_young.shape)
display(df_young.head())

print("\nImages:", len(df_young))
print("Patients:", df_young["patient_id"].nunique())
print("\nSex:")
print(df_young["label"].value_counts())

(116, 6)

,patient_id,image_name,path,label,age,age_group
0,2450,00002450_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,0,4,age_01_05
1,2555,00002555_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,1,5,age_01_05
2,4028,00004028_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,0,5,age_01_05
3,4535,00004535_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,0,5,age_01_05
4,4987,00004987_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,1,4,age_01_05

Images: 116
Patients: 103

Sex:
label
1    59
0    57
Name: count, dtype: int64

In [14]:
# from pediatric_resnet_ft import run_cv

# results = run_cv(
#     csv_path="/content/drive/MyDrive/QC/age_01_05.csv",

#     pretrained="none",
#     #pretrained_path="/content/drive/MyDrive/colab_最小データセット/models/resnet50_pa_adult.pt",

#     mode="layer4",

#     seeds=[42],
#     n_splits=5,

#     epochs=3,
#     batch_size=16,

#     id_col="patient_id",

#     output_dir="/content/drive/MyDrive/QC/results/test_young_layer4",
# )

In [15]:
# results = run_cv(
#     csv_path="/content/drive/MyDrive/QC/age_01_05.csv",

#     pretrained="imagenet",
#     #pretrained_path="/content/drive/MyDrive/colab_最小データセット/models/resnet50_pa_adult.pt",

#     mode="layer4",

#     seeds=[42],
#     n_splits=5,

#     epochs=3,
#     batch_size=16,

#     id_col="patient_id",

#     output_dir="/content/drive/MyDrive/QC/results/test_young_layer4",
# )

In [16]:
# import torch
# import os

# CKPT_PATH = (
#     "/content/drive/MyDrive/colab_最小データセット/models/"
#     "/resnet50_pa_adult_v4.pt"
# )

# WEIGHTS_PATH = (
#     "/content/drive/MyDrive/colab_最小データセット/models/"
#     "/resnet50_pa_adult_v4_weights.pt"
# )

# # 自分で作成した信頼できるcheckpointなので weights_only=False
# ckpt = torch.load(
#     CKPT_PATH,
#     map_location="cpu",
#     weights_only=False
# )

# print("Checkpoint keys:")
# print(ckpt.keys())

# # 今回のcheckpointではここ
# state_dict = ckpt["model_state_dict"]

# # 純粋なstate_dictだけ保存
# torch.save(
#     state_dict,
#     WEIGHTS_PATH
# )

# print("\nSaved:")
# print(WEIGHTS_PATH)
# print(f"Parameters/tensors: {len(state_dict)}")

In [17]:
from pediatric_resnet_ft import run_cv

results = run_cv(
    csv_path="/content/drive/MyDrive/QC/age_01_05.csv",

    pretrained="adult",
    pretrained_path="/content/drive/MyDrive/colab_最小データセット/models/Morimoto_Adult_AgeFixed_20260923_共有用/resnet50_pa_adult_agefixed_morimoto_20260923_weights.pt",

    mode="layer4",

    seeds=[42],
    n_splits=5,

    epochs=30,
    batch_size=16,

    id_col="patient_id",

    output_dir="/content/drive/MyDrive/QC/results/test_young_layer4",
)

Device: cuda (Tesla T4)
CV: 1 seed(s) x 5 folds = 5 models

Seed 1/1 (seed=42)
  Fold 1/5 | train=93 valid=23
    Epoch 01/30 | train loss=1.6216 AUC=0.6900 | val loss=4.1025 AUC=0.6333
    Epoch 02/30 | train loss=1.6314 AUC=0.6426 | val loss=2.6764 AUC=0.6333
    Epoch 03/30 | train loss=0.9638 AUC=0.7373 | val loss=1.9993 AUC=0.6333
    Epoch 04/30 | train loss=0.6561 AUC=0.8091 | val loss=1.6484 AUC=0.5778
    Epoch 05/30 | train loss=0.6006 AUC=0.8114 | val loss=1.5115 AUC=0.5667
    Epoch 06/30 | train loss=0.5148 AUC=0.8424 | val loss=1.3853 AUC=0.5333
    Epoch 07/30 | train loss=0.4286 AUC=0.8705 | val loss=1.2148 AUC=0.5778
    Epoch 08/30 | train loss=0.3631 AUC=0.9212 | val loss=1.2538 AUC=0.5889
    Epoch 09/30 | train loss=0.3682 AUC=0.9151 | val loss=1.2047 AUC=0.6111
    Epoch 10/30 | train loss=0.3337 AUC=0.9353 | val loss=1.0716 AUC=0.6333
    Epoch 11/30 | train loss=0.2688 AUC=0.9648 | val loss=1.0292 AUC=0.6333
    Epoch 12/30 | train loss=0.2899 AUC=0.9522 | val loss=1.0139 AUC=0.6333
    Epoch 13/30 | train loss=0.2377 AUC=0.9737 | val loss=1.0083 AUC=0.6667
    Epoch 14/30 | train loss=0.2201 AUC=0.9845 | val loss=0.9898 AUC=0.6667
    Epoch 15/30 | train loss=0.1928 AUC=0.9878 | val loss=1.1274 AUC=0.6444
    Epoch 16/30 | train loss=0.1285 AUC=0.9977 | val loss=1.1104 AUC=0.6444
    Epoch 17/30 | train loss=0.1558 AUC=0.9939 | val loss=1.1304 AUC=0.6222
    Epoch 18/30 | train loss=0.1144 AUC=0.9991 | val loss=1.1025 AUC=0.6444
    Epoch 19/30 | train loss=0.1652 AUC=0.9977 | val loss=1.0427 AUC=0.6333
    Epoch 20/30 | train loss=0.1327 AUC=0.9967 | val loss=1.0412 AUC=0.6333
    Epoch 21/30 | train loss=0.0878 AUC=1.0000 | val loss=1.0437 AUC=0.6333
    Epoch 22/30 | train loss=0.1299 AUC=0.9934 | val loss=0.9973 AUC=0.6444
    Epoch 23/30 | train loss=0.0786 AUC=1.0000 | val loss=1.0000 AUC=0.6444
    Epoch 24/30 | train loss=0.0827 AUC=1.0000 | val loss=1.0732 AUC=0.6444
    Epoch 25/30 | train loss=0.0806 AUC=1.0000 | val loss=1.0898 AUC=0.6333
    Epoch 26/30 | train loss=0.0931 AUC=1.0000 | val loss=1.0528 AUC=0.6333
    Epoch 27/30 | train loss=0.0738 AUC=1.0000 | val loss=1.0658 AUC=0.6556
    Epoch 28/30 | train loss=0.0845 AUC=1.0000 | val loss=1.0818 AUC=0.6667
    Epoch 29/30 | train loss=0.0929 AUC=0.9995 | val loss=1.1473 AUC=0.6444
    Epoch 30/30 | train loss=0.0941 AUC=0.9991 | val loss=1.1009 AUC=0.6333
  Fold 1/5 finished | best AUC=0.6667
  Fold 2/5 | train=93 valid=23
    Epoch 01/30 | train loss=2.1892 AUC=0.5873 | val loss=1.2010 AUC=0.6667
    Epoch 02/30 | train loss=1.2753 AUC=0.6737 | val loss=1.2115 AUC=0.6750
    Epoch 03/30 | train loss=0.8566 AUC=0.7512 | val loss=1.2110 AUC=0.6583
    Epoch 04/30 | train loss=0.7455 AUC=0.7722 | val loss=1.2125 AUC=0.6750
    Epoch 05/30 | train loss=0.5198 AUC=0.8459 | val loss=1.1244 AUC=0.6583
    Epoch 06/30 | train loss=0.4091 AUC=0.8954 | val loss=1.0435 AUC=0.6583
    Epoch 07/30 | train loss=0.4012 AUC=0.8978 | val loss=1.0357 AUC=0.6583
    Epoch 08/30 | train loss=0.2823 AUC=0.9608 | val loss=1.0942 AUC=0.6333
    Epoch 09/30 | train loss=0.2945 AUC=0.9454 | val loss=1.1793 AUC=0.6333
    Epoch 10/30 | train loss=0.2208 AUC=0.9734 | val loss=1.2258 AUC=0.6250
    Epoch 11/30 | train loss=0.2392 AUC=0.9734 | val loss=1.2280 AUC=0.6250
    Epoch 12/30 | train loss=0.1781 AUC=0.9818 | val loss=1.2339 AUC=0.6167
    Epoch 13/30 | train loss=0.1487 AUC=0.9953 | val loss=1.2439 AUC=0.6250
    Epoch 14/30 | train loss=0.1320 AUC=0.9972 | val loss=1.2603 AUC=0.6333
    Epoch 15/30 | train loss=0.1173 AUC=0.9977 | val loss=1.2699 AUC=0.6250
    Epoch 16/30 | train loss=0.1228 AUC=0.9963 | val loss=1.2968 AUC=0.6250
    Epoch 17/30 | train loss=0.0823 AUC=1.0000 | val loss=1.2985 AUC=0.6083
    Epoch 18/30 | train loss=0.1204 AUC=0.9949 | val loss=1.3483 AUC=0.6083
    Epoch 19/30 | train loss=0.0805 AUC=1.0000 | val loss=1.3673 AUC=0.5917
    Epoch 20/30 | train loss=0.1050 AUC=0.9972 | val loss=1.4022 AUC=0.5833
    Epoch 21/30 | train loss=0.1210 AUC=0.9939 | val loss=1.4454 AUC=0.5833
    Epoch 22/30 | train loss=0.0804 AUC=1.0000 | val loss=1.4551 AUC=0.5833
    Epoch 23/30 | train loss=0.0404 AUC=1.0000 | val loss=1.4579 AUC=0.5833
    Epoch 24/30 | train loss=0.0515 AUC=0.9995 | val loss=1.4604 AUC=0.5833
    Epoch 25/30 | train loss=0.0652 AUC=1.0000 | val loss=1.4743 AUC=0.5833
    Epoch 26/30 | train loss=0.0478 AUC=1.0000 | val loss=1.4749 AUC=0.5833
    Epoch 27/30 | train loss=0.0812 AUC=1.0000 | val loss=1.4944 AUC=0.5917
    Epoch 28/30 | train loss=0.0471 AUC=1.0000 | val loss=1.4740 AUC=0.5917
    Epoch 29/30 | train loss=0.0504 AUC=1.0000 | val loss=1.4362 AUC=0.5917
    Epoch 30/30 | train loss=0.0439 AUC=1.0000 | val loss=1.4766 AUC=0.5833
  Fold 2/5 finished | best AUC=0.6750
  Fold 3/5 | train=94 valid=22
    Epoch 01/30 | train loss=2.1201 AUC=0.6073 | val loss=1.9825 AUC=0.7417
    Epoch 02/30 | train loss=1.6207 AUC=0.6148 | val loss=1.2459 AUC=0.7417
    Epoch 03/30 | train loss=0.9723 AUC=0.7279 | val loss=0.9630 AUC=0.7417
    Epoch 04/30 | train loss=0.6768 AUC=0.7877 | val loss=0.8679 AUC=0.7500
    Epoch 05/30 | train loss=0.5737 AUC=0.8189 | val loss=0.8287 AUC=0.7583
    Epoch 06/30 | train loss=0.5150 AUC=0.8298 | val loss=0.7645 AUC=0.7417
    Epoch 07/30 | train loss=0.3695 AUC=0.9113 | val loss=0.7452 AUC=0.7333
    Epoch 08/30 | train loss=0.3735 AUC=0.9081 | val loss=0.7462 AUC=0.7333
    Epoch 09/30 | train loss=0.3221 AUC=0.9430 | val loss=0.7646 AUC=0.7250
    Epoch 10/30 | train loss=0.2606 AUC=0.9801 | val loss=0.7850 AUC=0.7250
    Epoch 11/30 | train loss=0.2414 AUC=0.9679 | val loss=0.7960 AUC=0.7333
    Epoch 12/30 | train loss=0.1974 AUC=0.9873 | val loss=0.8185 AUC=0.7333
    Epoch 13/30 | train loss=0.1878 AUC=0.9869 | val loss=0.8398 AUC=0.7250
    Epoch 14/30 | train loss=0.1587 AUC=0.9941 | val loss=0.8562 AUC=0.7083
    Epoch 15/30 | train loss=0.1200 AUC=1.0000 | val loss=0.8779 AUC=0.6917
    Epoch 16/30 | train loss=0.1131 AUC=0.9995 | val loss=0.8941 AUC=0.7000
    Epoch 17/30 | train loss=0.1443 AUC=0.9932 | val loss=0.9066 AUC=0.7333
    Epoch 18/30 | train loss=0.1054 AUC=0.9991 | val loss=0.9049 AUC=0.7000
    Epoch 19/30 | train loss=0.1060 AUC=0.9986 | val loss=0.9136 AUC=0.7000
    Epoch 20/30 | train loss=0.0988 AUC=0.9973 | val loss=0.9239 AUC=0.6917
    Epoch 21/30 | train loss=0.1121 AUC=0.9982 | val loss=0.9544 AUC=0.7000
    Epoch 22/30 | train loss=0.0658 AUC=1.0000 | val loss=0.9494 AUC=0.7000
    Epoch 23/30 | train loss=0.0625 AUC=1.0000 | val loss=0.9723 AUC=0.7000
    Epoch 24/30 | train loss=0.0676 AUC=1.0000 | val loss=0.9923 AUC=0.6917
    Epoch 25/30 | train loss=0.0827 AUC=0.9991 | val loss=1.0160 AUC=0.6833
    Epoch 26/30 | train loss=0.0726 AUC=1.0000 | val loss=1.0055 AUC=0.6917
    Epoch 27/30 | train loss=0.0713 AUC=1.0000 | val loss=0.9877 AUC=0.6917
    Epoch 28/30 | train loss=0.0714 AUC=0.9995 | val loss=0.9871 AUC=0.6833
    Epoch 29/30 | train loss=0.0941 AUC=0.9973 | val loss=0.9841 AUC=0.6917
    Epoch 30/30 | train loss=0.0753 AUC=0.9991 | val loss=0.9722 AUC=0.6917
  Fold 3/5 finished | best AUC=0.7583
  Fold 4/5 | train=91 valid=25
    Epoch 01/30 | train loss=1.8404 AUC=0.6353 | val loss=2.1360 AUC=0.5897
    Epoch 02/30 | train loss=1.3307 AUC=0.6981 | val loss=1.7737 AUC=0.6090
    Epoch 03/30 | train loss=0.8554 AUC=0.7990 | val loss=1.5356 AUC=0.6282
    Epoch 04/30 | train loss=0.7611 AUC=0.7720 | val loss=1.3004 AUC=0.6474
    Epoch 05/30 | train loss=0.6687 AUC=0.7923 | val loss=1.1714 AUC=0.6538
    Epoch 06/30 | train loss=0.5159 AUC=0.8483 | val loss=1.0878 AUC=0.6538
    Epoch 07/30 | train loss=0.4760 AUC=0.8570 | val loss=1.0179 AUC=0.6603
    Epoch 08/30 | train loss=0.4012 AUC=0.8990 | val loss=0.9651 AUC=0.6603
    Epoch 09/30 | train loss=0.3757 AUC=0.9072 | val loss=0.9200 AUC=0.6603
    Epoch 10/30 | train loss=0.2565 AUC=0.9686 | val loss=0.9016 AUC=0.6731
    Epoch 11/30 | train loss=0.2871 AUC=0.9599 | val loss=0.9080 AUC=0.6795
    Epoch 12/30 | train loss=0.2720 AUC=0.9652 | val loss=0.9214 AUC=0.6731
    Epoch 13/30 | train loss=0.2026 AUC=0.9879 | val loss=0.8968 AUC=0.6795
    Epoch 14/30 | train loss=0.1691 AUC=0.9908 | val loss=0.9003 AUC=0.6795
    Epoch 15/30 | train loss=0.1691 AUC=0.9932 | val loss=0.9096 AUC=0.6795
    Epoch 16/30 | train loss=0.1386 AUC=0.9928 | val loss=0.9134 AUC=0.6859
    Epoch 17/30 | train loss=0.1507 AUC=0.9942 | val loss=0.9145 AUC=0.6923
    Epoch 18/30 | train loss=0.1519 AUC=0.9894 | val loss=0.9525 AUC=0.6795
    Epoch 19/30 | train loss=0.0970 AUC=1.0000 | val loss=0.9220 AUC=0.7051
    Epoch 20/30 | train loss=0.1221 AUC=0.9986 | val loss=0.9102 AUC=0.7051
    Epoch 21/30 | train loss=0.0810 AUC=1.0000 | val loss=0.9382 AUC=0.6987
    Epoch 22/30 | train loss=0.0649 AUC=1.0000 | val loss=0.9462 AUC=0.6923
    Epoch 23/30 | train loss=0.0733 AUC=1.0000 | val loss=0.9398 AUC=0.6987
    Epoch 24/30 | train loss=0.1056 AUC=0.9995 | val loss=0.9379 AUC=0.7051
    Epoch 25/30 | train loss=0.0535 AUC=1.0000 | val loss=0.9296 AUC=0.7051
    Epoch 26/30 | train loss=0.0763 AUC=1.0000 | val loss=0.9432 AUC=0.7051
    Epoch 27/30 | train loss=0.0898 AUC=0.9981 | val loss=0.9388 AUC=0.7051
    Epoch 28/30 | train loss=0.1086 AUC=0.9990 | val loss=0.9350 AUC=0.7051
    Epoch 29/30 | train loss=0.0820 AUC=1.0000 | val loss=0.9301 AUC=0.7051
    Epoch 30/30 | train loss=0.0982 AUC=0.9995 | val loss=0.9311 AUC=0.7051
  Fold 4/5 finished | best AUC=0.7051
  Fold 5/5 | train=93 valid=23
    Epoch 01/30 | train loss=1.9839 AUC=0.6363 | val loss=1.6550 AUC=0.5833
    Epoch 02/30 | train loss=1.2657 AUC=0.7007 | val loss=1.3730 AUC=0.5750
    Epoch 03/30 | train loss=0.9503 AUC=0.7470 | val loss=1.3166 AUC=0.5917
    Epoch 04/30 | train loss=0.6696 AUC=0.8007 | val loss=1.3113 AUC=0.5917
    Epoch 05/30 | train loss=0.5701 AUC=0.8240 | val loss=1.3192 AUC=0.5917
    Epoch 06/30 | train loss=0.5270 AUC=0.8287 | val loss=1.2395 AUC=0.5917
    Epoch 07/30 | train loss=0.4099 AUC=0.8898 | val loss=1.2006 AUC=0.5833
    Epoch 08/30 | train loss=0.2872 AUC=0.9524 | val loss=1.1938 AUC=0.5833
    Epoch 09/30 | train loss=0.2743 AUC=0.9566 | val loss=1.1480 AUC=0.5750
    Epoch 10/30 | train loss=0.2334 AUC=0.9659 | val loss=1.1804 AUC=0.5667
    Epoch 11/30 | train loss=0.2119 AUC=0.9715 | val loss=1.2036 AUC=0.5583
    Epoch 12/30 | train loss=0.2359 AUC=0.9636 | val loss=1.1984 AUC=0.5667
    Epoch 13/30 | train loss=0.1784 AUC=0.9981 | val loss=1.2352 AUC=0.5583
    Epoch 14/30 | train loss=0.1868 AUC=0.9804 | val loss=1.2650 AUC=0.5333
    Epoch 15/30 | train loss=0.1263 AUC=0.9967 | val loss=1.3019 AUC=0.5500
    Epoch 16/30 | train loss=0.1121 AUC=0.9977 | val loss=1.3761 AUC=0.5417
    Epoch 17/30 | train loss=0.1063 AUC=0.9991 | val loss=1.3767 AUC=0.5417
    Epoch 18/30 | train loss=0.1067 AUC=0.9995 | val loss=1.3889 AUC=0.5417
    Epoch 19/30 | train loss=0.1039 AUC=0.9986 | val loss=1.3982 AUC=0.5250
    Epoch 20/30 | train loss=0.1278 AUC=0.9958 | val loss=1.4213 AUC=0.5250
    Epoch 21/30 | train loss=0.0932 AUC=0.9991 | val loss=1.4318 AUC=0.5250
    Epoch 22/30 | train loss=0.0779 AUC=1.0000 | val loss=1.4416 AUC=0.5250
    Epoch 23/30 | train loss=0.0739 AUC=1.0000 | val loss=1.4612 AUC=0.5167
    Epoch 24/30 | train loss=0.0668 AUC=1.0000 | val loss=1.4352 AUC=0.5083
    Epoch 25/30 | train loss=0.0840 AUC=0.9995 | val loss=1.4880 AUC=0.5167
    Epoch 26/30 | train loss=0.0771 AUC=0.9995 | val loss=1.4978 AUC=0.5333
    Epoch 27/30 | train loss=0.0898 AUC=0.9981 | val loss=1.5013 AUC=0.5333
    Epoch 28/30 | train loss=0.0676 AUC=1.0000 | val loss=1.5023 AUC=0.5250
    Epoch 29/30 | train loss=0.0591 AUC=1.0000 | val loss=1.5189 AUC=0.5250
    Epoch 30/30 | train loss=0.0579 AUC=1.0000 | val loss=1.5019 AUC=0.5333
  Fold 5/5 finished | best AUC=0.5917
Seed 42 OOF AUC = 0.6399

Finished. Mean-prediction OOF AUC = 0.6399
Saved to: /content/drive/MyDrive/QC/results/test_young_layer4

In [18]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

# ============================================================
# Settings
# ============================================================
OOF_PATH = (
    "/content/drive/MyDrive/QC/results/"
    "test_young_layer4/oof_predictions.csv"
)

PATIENT_COL = "patient_id"
LABEL_COL = "label"

SEEDS = [42, ]
#SEEDS = [42, 43, 44, 45, 46]   # 本解析では5 seeds
N_BOOT = 2000
RANDOM_STATE = 12345


# ============================================================
# Load
# ============================================================
df = pd.read_csv(OOF_PATH)

pred_cols = [f"oof_seed{s}" for s in SEEDS]

missing = [c for c in pred_cols if c not in df.columns]
if missing:
    raise ValueError(
        f"Missing prediction columns: {missing}\n"
        "まだ1 seedしか実行していない場合は SEEDS=[42] にしてください。"
    )

print("Images:", len(df))
print("Patients:", df[PATIENT_COL].nunique())


# ============================================================
# 1. Patient-level aggregation
#    複数画像を持つ患者では予測確率を平均
# ============================================================
# 患者内でlabelが一貫しているか確認
label_check = df.groupby(PATIENT_COL)[LABEL_COL].nunique()

if (label_check > 1).any():
    bad_ids = label_check[label_check > 1].index.tolist()
    raise ValueError(
        f"同一患者内でlabelが不一致です: {bad_ids[:10]}"
    )

agg_dict = {
    LABEL_COL: "first",
}

for col in pred_cols:
    agg_dict[col] = "mean"

patient_df = (
    df.groupby(PATIENT_COL, as_index=False)
      .agg(agg_dict)
)

print("\nPatient-level dataset")
print(patient_df.shape)
print(patient_df[LABEL_COL].value_counts())


# ============================================================
# 2. Seedごとの patient-level OOF AUROC
# ============================================================
seed_results = []

y = patient_df[LABEL_COL].astype(int).to_numpy()

for seed in SEEDS:
    col = f"oof_seed{seed}"
    pred = patient_df[col].to_numpy()

    auc = roc_auc_score(y, pred)

    seed_results.append({
        "seed": seed,
        "patient_level_auc": auc
    })

seed_results = pd.DataFrame(seed_results)

mean_auc = seed_results["patient_level_auc"].mean()

# sample SD
sd_auc = seed_results["patient_level_auc"].std(ddof=1) if len(SEEDS) > 1 else np.nan


# ============================================================
# 3. Primary prediction
#    5 seedsのpatient-level OOF予測を平均
# ============================================================
patient_df["oof_mean_seeds"] = patient_df[pred_cols].mean(axis=1)

primary_pred = patient_df["oof_mean_seeds"].to_numpy()

primary_auc = roc_auc_score(y, primary_pred)


# ============================================================
# 4. Patient-level stratified bootstrap
#
#    患者単位でresampling。
#    Female / Maleをそれぞれ復元抽出してclass balanceを保持。
# ============================================================
def bootstrap_auc_patient_level(
    y_true,
    y_pred,
    n_boot=5000,
    random_state=12345
):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)

    rng = np.random.default_rng(random_state)

    idx0 = np.where(y_true == 0)[0]
    idx1 = np.where(y_true == 1)[0]

    boot_aucs = []

    for _ in range(n_boot):

        # classごとにpatientを復元抽出
        boot0 = rng.choice(
            idx0,
            size=len(idx0),
            replace=True
        )

        boot1 = rng.choice(
            idx1,
            size=len(idx1),
            replace=True
        )

        boot_idx = np.concatenate([boot0, boot1])

        auc = roc_auc_score(
            y_true[boot_idx],
            y_pred[boot_idx]
        )

        boot_aucs.append(auc)

    boot_aucs = np.asarray(boot_aucs)

    ci_lower = np.percentile(boot_aucs, 2.5)
    ci_upper = np.percentile(boot_aucs, 97.5)

    return ci_lower, ci_upper, boot_aucs


ci_low, ci_high, boot_aucs = bootstrap_auc_patient_level(
    y,
    primary_pred,
    n_boot=N_BOOT,
    random_state=RANDOM_STATE
)


# ============================================================
# 5. Results
# ============================================================
print("\n==========================================")
print("PRIMARY ANALYSIS")
print("==========================================")

print(
    f"Patient-level AUROC = {primary_auc:.3f} "
    f"(95% CI {ci_low:.3f}-{ci_high:.3f})"
)

print("\n==========================================")
print("SEED-LEVEL REPRODUCIBILITY")
print("==========================================")

display(seed_results)

if len(SEEDS) > 1:
    print(
        f"5-seed AUROC mean ± SD = "
        f"{mean_auc:.3f} ± {sd_auc:.3f}"
    )
else:
    print(
        f"Seed {SEEDS[0]} AUROC = {mean_auc:.3f}"
    )


# ============================================================
# 6. Save
# ============================================================
summary = pd.DataFrame([{
    "n_patients": len(patient_df),
    "primary_patient_auc": primary_auc,
    "bootstrap_ci_lower": ci_low,
    "bootstrap_ci_upper": ci_high,
    "n_bootstrap": N_BOOT,
    "seed_auc_mean": mean_auc,
    "seed_auc_sd": sd_auc,
    "n_seeds": len(SEEDS),
}])

summary.to_csv(
    "/content/drive/MyDrive/QC/results/"
    "patient_level_auc_summary.csv",
    index=False
)

seed_results.to_csv(
    "/content/drive/MyDrive/QC/results/"
    "patient_level_seed_auc.csv",
    index=False
)

patient_df.to_csv(
    "/content/drive/MyDrive/QC/results/"
    "patient_level_oof_predictions.csv",
    index=False
)

print("\nSaved.")

Images: 116
Patients: 103

Patient-level dataset
(103, 3)
label
1    54
0    49
Name: count, dtype: int64

==========================================
PRIMARY ANALYSIS
==========================================
Patient-level AUROC = 0.641 (95% CI 0.536-0.749)

==========================================
SEED-LEVEL REPRODUCIBILITY
==========================================

   seed  patient_level_auc
0    42           0.640967

Seed 42 AUROC = 0.641

Saved.

# 6-11

In [19]:
from pediatric_resnet_ft import build_dataset_csv

df_young = build_dataset_csv(
    metadata_path="/content/drive/MyDrive/PedAI_ChestXp/For_finetuning/QC/merged_reviewer_results_260906.xlsx",
    image_dir="/content/drive/MyDrive/PedAI_ChestXp/For_finetuning/QC/age_06_11",
    output_csv="/content/drive/MyDrive/QC/age_06_11.csv",
)

print(df_young.shape)
display(df_young.head())

print("\nImages:", len(df_young))
print("Patients:", df_young["patient_id"].nunique())
print("\nSex:")
print(df_young["label"].value_counts())

(404, 6)

,patient_id,image_name,path,label,age,age_group
0,1485,00001485_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,0,11,age_06_11
1,1676,00001676_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,0,8,age_06_11
2,1676,00001676_001.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,0,11,age_06_11
3,1717,00001717_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,0,9,age_06_11
4,1717,00001717_001.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,0,9,age_06_11

Images: 404
Patients: 296

Sex:
label
1    219
0    185
Name: count, dtype: int64

In [20]:
from pediatric_resnet_ft import run_cv

results = run_cv(
    csv_path="/content/drive/MyDrive/QC/age_06_11.csv",

    pretrained="adult",
    pretrained_path="/content/drive/MyDrive/colab_最小データセット/models/Morimoto_Adult_AgeFixed_20260923_共有用/resnet50_pa_adult_agefixed_morimoto_20260923_weights.pt",

    mode="layer4",

    seeds=[42],
    n_splits=5,

    epochs=30,
    batch_size=16,

    id_col="patient_id",

    output_dir="/content/drive/MyDrive/QC/results/test_school_layer4",
)

Device: cuda (Tesla T4)
CV: 1 seed(s) x 5 folds = 5 models

Seed 1/1 (seed=42)
  Fold 1/5 | train=327 valid=77
    Epoch 01/30 | train loss=1.5833 AUC=0.6975 | val loss=0.9684 AUC=0.6838
    Epoch 02/30 | train loss=0.7289 AUC=0.7797 | val loss=0.7479 AUC=0.7000
    Epoch 03/30 | train loss=0.6000 AUC=0.7862 | val loss=0.6640 AUC=0.7142
    Epoch 04/30 | train loss=0.4968 AUC=0.8382 | val loss=0.6261 AUC=0.7338
    Epoch 05/30 | train loss=0.4228 AUC=0.8949 | val loss=0.6275 AUC=0.7439
    Epoch 06/30 | train loss=0.3926 AUC=0.9108 | val loss=0.6300 AUC=0.7493
    Epoch 07/30 | train loss=0.3182 AUC=0.9531 | val loss=0.6310 AUC=0.7486
    Epoch 08/30 | train loss=0.2766 AUC=0.9645 | val loss=0.6316 AUC=0.7595
    Epoch 09/30 | train loss=0.1963 AUC=0.9872 | val loss=0.7272 AUC=0.7655
    Epoch 10/30 | train loss=0.1389 AUC=0.9919 | val loss=0.6977 AUC=0.7689
    Epoch 11/30 | train loss=0.1090 AUC=0.9970 | val loss=0.7389 AUC=0.7750
    Epoch 12/30 | train loss=0.0648 AUC=0.9995 | val loss=0.7206 AUC=0.7797
    Epoch 13/30 | train loss=0.0479 AUC=0.9998 | val loss=0.7591 AUC=0.7831
    Epoch 14/30 | train loss=0.0427 AUC=1.0000 | val loss=0.7767 AUC=0.7865
    Epoch 15/30 | train loss=0.0378 AUC=0.9999 | val loss=0.7876 AUC=0.7764
    Epoch 16/30 | train loss=0.0284 AUC=1.0000 | val loss=0.8072 AUC=0.7818
    Epoch 17/30 | train loss=0.0290 AUC=0.9998 | val loss=0.7932 AUC=0.7736
    Epoch 18/30 | train loss=0.0228 AUC=1.0000 | val loss=0.8375 AUC=0.7764
    Epoch 19/30 | train loss=0.0172 AUC=1.0000 | val loss=0.8222 AUC=0.7655
    Epoch 20/30 | train loss=0.0144 AUC=1.0000 | val loss=0.8339 AUC=0.7791
    Epoch 21/30 | train loss=0.0109 AUC=1.0000 | val loss=0.8194 AUC=0.7784
    Epoch 22/30 | train loss=0.0233 AUC=0.9999 | val loss=0.8186 AUC=0.7824
    Epoch 23/30 | train loss=0.0121 AUC=1.0000 | val loss=0.8210 AUC=0.7716
    Epoch 24/30 | train loss=0.0115 AUC=1.0000 | val loss=0.8378 AUC=0.7764
    Epoch 25/30 | train loss=0.0108 AUC=1.0000 | val loss=0.8382 AUC=0.7764
    Epoch 26/30 | train loss=0.0133 AUC=1.0000 | val loss=0.8321 AUC=0.7777
    Epoch 27/30 | train loss=0.0174 AUC=1.0000 | val loss=0.8539 AUC=0.7703
    Epoch 28/30 | train loss=0.0108 AUC=1.0000 | val loss=0.8519 AUC=0.7818
    Epoch 29/30 | train loss=0.0110 AUC=1.0000 | val loss=0.8487 AUC=0.7750
    Epoch 30/30 | train loss=0.0079 AUC=1.0000 | val loss=0.8717 AUC=0.7770
  Fold 1/5 finished | best AUC=0.7865
  Fold 2/5 | train=320 valid=84
    Epoch 01/30 | train loss=1.6299 AUC=0.7007 | val loss=0.9518 AUC=0.7708
    Epoch 02/30 | train loss=0.7724 AUC=0.7632 | val loss=0.6838 AUC=0.7373
    Epoch 03/30 | train loss=0.5829 AUC=0.7852 | val loss=0.6296 AUC=0.7587
    Epoch 04/30 | train loss=0.5008 AUC=0.8365 | val loss=0.6000 AUC=0.7685
    Epoch 05/30 | train loss=0.4492 AUC=0.8743 | val loss=0.5911 AUC=0.7679
    Epoch 06/30 | train loss=0.3687 AUC=0.9339 | val loss=0.5965 AUC=0.7853
    Epoch 07/30 | train loss=0.3242 AUC=0.9498 | val loss=0.6051 AUC=0.7581
    Epoch 08/30 | train loss=0.2778 AUC=0.9638 | val loss=0.6281 AUC=0.7517
    Epoch 09/30 | train loss=0.2134 AUC=0.9812 | val loss=0.6893 AUC=0.7361
    Epoch 10/30 | train loss=0.1693 AUC=0.9885 | val loss=0.7223 AUC=0.7309
    Epoch 11/30 | train loss=0.0794 AUC=0.9997 | val loss=0.7490 AUC=0.7546
    Epoch 12/30 | train loss=0.0724 AUC=0.9977 | val loss=0.7349 AUC=0.7593
    Epoch 13/30 | train loss=0.0511 AUC=0.9998 | val loss=0.8205 AUC=0.7367
    Epoch 14/30 | train loss=0.0406 AUC=1.0000 | val loss=0.7998 AUC=0.7593
    Epoch 15/30 | train loss=0.0270 AUC=1.0000 | val loss=0.8302 AUC=0.7639
    Epoch 16/30 | train loss=0.0417 AUC=0.9991 | val loss=0.8425 AUC=0.7506
    Epoch 17/30 | train loss=0.0226 AUC=1.0000 | val loss=0.8457 AUC=0.7587
    Epoch 18/30 | train loss=0.0246 AUC=1.0000 | val loss=0.8570 AUC=0.7512
    Epoch 19/30 | train loss=0.0147 AUC=1.0000 | val loss=0.8711 AUC=0.7500
    Epoch 20/30 | train loss=0.0121 AUC=1.0000 | val loss=0.8721 AUC=0.7575
    Epoch 21/30 | train loss=0.0147 AUC=1.0000 | val loss=0.8961 AUC=0.7552
    Epoch 22/30 | train loss=0.0165 AUC=1.0000 | val loss=0.9141 AUC=0.7483
    Epoch 23/30 | train loss=0.0187 AUC=1.0000 | val loss=0.8865 AUC=0.7598
    Epoch 24/30 | train loss=0.0121 AUC=1.0000 | val loss=0.8936 AUC=0.7523
    Epoch 25/30 | train loss=0.0113 AUC=1.0000 | val loss=0.9110 AUC=0.7558
    Epoch 26/30 | train loss=0.0134 AUC=1.0000 | val loss=0.9339 AUC=0.7546
    Epoch 27/30 | train loss=0.0147 AUC=1.0000 | val loss=0.9288 AUC=0.7529
    Epoch 28/30 | train loss=0.0165 AUC=1.0000 | val loss=0.9265 AUC=0.7488
    Epoch 29/30 | train loss=0.0132 AUC=1.0000 | val loss=0.9255 AUC=0.7517
    Epoch 30/30 | train loss=0.0143 AUC=1.0000 | val loss=0.9389 AUC=0.7523
  Fold 2/5 finished | best AUC=0.7853
  Fold 3/5 | train=318 valid=86
    Epoch 01/30 | train loss=1.5963 AUC=0.6957 | val loss=1.4080 AUC=0.7430
    Epoch 02/30 | train loss=0.7534 AUC=0.7527 | val loss=0.9262 AUC=0.7358
    Epoch 03/30 | train loss=0.5467 AUC=0.8038 | val loss=0.7635 AUC=0.7281
    Epoch 04/30 | train loss=0.4872 AUC=0.8461 | val loss=0.7604 AUC=0.7297
    Epoch 05/30 | train loss=0.4058 AUC=0.9021 | val loss=0.8293 AUC=0.7275
    Epoch 06/30 | train loss=0.3976 AUC=0.9037 | val loss=0.8477 AUC=0.7209
    Epoch 07/30 | train loss=0.3305 AUC=0.9492 | val loss=0.8297 AUC=0.7082
    Epoch 08/30 | train loss=0.2512 AUC=0.9758 | val loss=0.8784 AUC=0.6966
    Epoch 09/30 | train loss=0.1715 AUC=0.9903 | val loss=0.9698 AUC=0.6994
    Epoch 10/30 | train loss=0.1331 AUC=0.9946 | val loss=1.0192 AUC=0.7038
    Epoch 11/30 | train loss=0.0951 AUC=0.9996 | val loss=1.1067 AUC=0.7093
    Epoch 12/30 | train loss=0.0648 AUC=0.9983 | val loss=1.1324 AUC=0.6884
    Epoch 13/30 | train loss=0.0768 AUC=0.9985 | val loss=1.0527 AUC=0.6724
    Epoch 14/30 | train loss=0.0307 AUC=1.0000 | val loss=1.1259 AUC=0.6961
    Epoch 15/30 | train loss=0.0245 AUC=1.0000 | val loss=1.1679 AUC=0.7093
    Epoch 16/30 | train loss=0.0258 AUC=1.0000 | val loss=1.2422 AUC=0.6906
    Epoch 17/30 | train loss=0.0223 AUC=1.0000 | val loss=1.2495 AUC=0.6856
    Epoch 18/30 | train loss=0.0203 AUC=1.0000 | val loss=1.2759 AUC=0.6834
    Epoch 19/30 | train loss=0.0151 AUC=1.0000 | val loss=1.3100 AUC=0.6768
    Epoch 20/30 | train loss=0.0171 AUC=1.0000 | val loss=1.2908 AUC=0.6817
    Epoch 21/30 | train loss=0.0267 AUC=0.9999 | val loss=1.2885 AUC=0.6801
    Epoch 22/30 | train loss=0.0225 AUC=0.9999 | val loss=1.3020 AUC=0.6735
    Epoch 23/30 | train loss=0.0140 AUC=1.0000 | val loss=1.3266 AUC=0.6773
    Epoch 24/30 | train loss=0.0176 AUC=1.0000 | val loss=1.3042 AUC=0.6823
    Epoch 25/30 | train loss=0.0107 AUC=1.0000 | val loss=1.2890 AUC=0.6784
    Epoch 26/30 | train loss=0.0119 AUC=1.0000 | val loss=1.2867 AUC=0.6795
    Epoch 27/30 | train loss=0.0123 AUC=1.0000 | val loss=1.3154 AUC=0.6817
    Epoch 28/30 | train loss=0.0129 AUC=1.0000 | val loss=1.2896 AUC=0.6806
    Epoch 29/30 | train loss=0.0080 AUC=1.0000 | val loss=1.3065 AUC=0.6817
    Epoch 30/30 | train loss=0.0153 AUC=1.0000 | val loss=1.3096 AUC=0.6784
  Fold 3/5 finished | best AUC=0.7430
  Fold 4/5 | train=328 valid=76
    Epoch 01/30 | train loss=1.5520 AUC=0.7093 | val loss=1.2539 AUC=0.6376
    Epoch 02/30 | train loss=0.7624 AUC=0.7587 | val loss=0.8414 AUC=0.6566
    Epoch 03/30 | train loss=0.5672 AUC=0.8000 | val loss=0.7055 AUC=0.6772
    Epoch 04/30 | train loss=0.4861 AUC=0.8520 | val loss=0.7058 AUC=0.6772
    Epoch 05/30 | train loss=0.4348 AUC=0.8823 | val loss=0.6976 AUC=0.6779
    Epoch 06/30 | train loss=0.3953 AUC=0.9120 | val loss=0.6952 AUC=0.6904
    Epoch 07/30 | train loss=0.3509 AUC=0.9378 | val loss=0.6846 AUC=0.7051
    Epoch 08/30 | train loss=0.2855 AUC=0.9642 | val loss=0.6880 AUC=0.7109
    Epoch 09/30 | train loss=0.2098 AUC=0.9859 | val loss=0.7004 AUC=0.7036
    Epoch 10/30 | train loss=0.1355 AUC=0.9959 | val loss=0.8232 AUC=0.7058
    Epoch 11/30 | train loss=0.1240 AUC=0.9955 | val loss=0.8317 AUC=0.7051
    Epoch 12/30 | train loss=0.0857 AUC=0.9991 | val loss=0.8677 AUC=0.7117
    Epoch 13/30 | train loss=0.0512 AUC=0.9993 | val loss=0.9125 AUC=0.7043
    Epoch 14/30 | train loss=0.0544 AUC=0.9990 | val loss=0.8781 AUC=0.7124
    Epoch 15/30 | train loss=0.0240 AUC=1.0000 | val loss=0.9441 AUC=0.7219
    Epoch 16/30 | train loss=0.0331 AUC=1.0000 | val loss=0.9956 AUC=0.7095
    Epoch 17/30 | train loss=0.0222 AUC=1.0000 | val loss=1.0908 AUC=0.7029
    Epoch 18/30 | train loss=0.0147 AUC=1.0000 | val loss=1.0968 AUC=0.7007
    Epoch 19/30 | train loss=0.0164 AUC=1.0000 | val loss=1.0453 AUC=0.7036
    Epoch 20/30 | train loss=0.0159 AUC=1.0000 | val loss=1.0308 AUC=0.7080
    Epoch 21/30 | train loss=0.0118 AUC=1.0000 | val loss=1.0817 AUC=0.7065
    Epoch 22/30 | train loss=0.0175 AUC=0.9999 | val loss=1.0720 AUC=0.7043
    Epoch 23/30 | train loss=0.0084 AUC=1.0000 | val loss=1.0115 AUC=0.7117
    Epoch 24/30 | train loss=0.0137 AUC=1.0000 | val loss=1.0595 AUC=0.7109
    Epoch 25/30 | train loss=0.0125 AUC=1.0000 | val loss=1.0760 AUC=0.7058
    Epoch 26/30 | train loss=0.0103 AUC=1.0000 | val loss=1.0783 AUC=0.7102
    Epoch 27/30 | train loss=0.0135 AUC=1.0000 | val loss=1.0782 AUC=0.7058
    Epoch 28/30 | train loss=0.0154 AUC=1.0000 | val loss=1.1365 AUC=0.7065
    Epoch 29/30 | train loss=0.0117 AUC=1.0000 | val loss=1.0817 AUC=0.7080
    Epoch 30/30 | train loss=0.0082 AUC=1.0000 | val loss=1.0653 AUC=0.7109
  Fold 4/5 finished | best AUC=0.7219
  Fold 5/5 | train=323 valid=81
    Epoch 01/30 | train loss=1.6508 AUC=0.7014 | val loss=0.9422 AUC=0.7613
    Epoch 02/30 | train loss=0.8080 AUC=0.7489 | val loss=0.6655 AUC=0.7662
    Epoch 03/30 | train loss=0.5743 AUC=0.7954 | val loss=0.6058 AUC=0.7687
    Epoch 04/30 | train loss=0.4981 AUC=0.8373 | val loss=0.6063 AUC=0.7815
    Epoch 05/30 | train loss=0.4827 AUC=0.8447 | val loss=0.5905 AUC=0.7754
    Epoch 06/30 | train loss=0.4388 AUC=0.8854 | val loss=0.5825 AUC=0.7650
    Epoch 07/30 | train loss=0.3649 AUC=0.9323 | val loss=0.6048 AUC=0.7613
    Epoch 08/30 | train loss=0.3225 AUC=0.9595 | val loss=0.6127 AUC=0.7632
    Epoch 09/30 | train loss=0.2922 AUC=0.9637 | val loss=0.6000 AUC=0.7809
    Epoch 10/30 | train loss=0.2254 AUC=0.9856 | val loss=0.6290 AUC=0.7821
    Epoch 11/30 | train loss=0.1576 AUC=0.9958 | val loss=0.6543 AUC=0.7693
    Epoch 12/30 | train loss=0.1130 AUC=0.9964 | val loss=0.7170 AUC=0.7705
    Epoch 13/30 | train loss=0.0810 AUC=0.9998 | val loss=0.7246 AUC=0.7742
    Epoch 14/30 | train loss=0.0524 AUC=0.9998 | val loss=0.7397 AUC=0.7803
    Epoch 15/30 | train loss=0.0485 AUC=0.9998 | val loss=0.7832 AUC=0.7699
    Epoch 16/30 | train loss=0.0365 AUC=0.9999 | val loss=0.7994 AUC=0.7595
    Epoch 17/30 | train loss=0.0424 AUC=0.9998 | val loss=0.7955 AUC=0.7705
    Epoch 18/30 | train loss=0.0373 AUC=1.0000 | val loss=0.7939 AUC=0.7625
    Epoch 19/30 | train loss=0.0278 AUC=1.0000 | val loss=0.8276 AUC=0.7613
    Epoch 20/30 | train loss=0.0299 AUC=0.9999 | val loss=0.8263 AUC=0.7589
    Epoch 21/30 | train loss=0.0167 AUC=1.0000 | val loss=0.8308 AUC=0.7558
    Epoch 22/30 | train loss=0.0253 AUC=1.0000 | val loss=0.8257 AUC=0.7595
    Epoch 23/30 | train loss=0.0283 AUC=1.0000 | val loss=0.8167 AUC=0.7607
    Epoch 24/30 | train loss=0.0144 AUC=1.0000 | val loss=0.8434 AUC=0.7558
    Epoch 25/30 | train loss=0.0150 AUC=1.0000 | val loss=0.9028 AUC=0.7528
    Epoch 26/30 | train loss=0.0178 AUC=1.0000 | val loss=0.8334 AUC=0.7656
    Epoch 27/30 | train loss=0.0189 AUC=1.0000 | val loss=0.8304 AUC=0.7674
    Epoch 28/30 | train loss=0.0176 AUC=1.0000 | val loss=0.8537 AUC=0.7607
    Epoch 29/30 | train loss=0.0206 AUC=1.0000 | val loss=0.8436 AUC=0.7650
    Epoch 30/30 | train loss=0.0200 AUC=1.0000 | val loss=0.8842 AUC=0.7589
  Fold 5/5 finished | best AUC=0.7821
Seed 42 OOF AUC = 0.7488

Finished. Mean-prediction OOF AUC = 0.7488
Saved to: /content/drive/MyDrive/QC/results/test_school_layer4

In [21]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

# ============================================================
# Settings
# ============================================================
OOF_PATH = (
    "/content/drive/MyDrive/QC/results/"
    "test_school_layer4/oof_predictions.csv"
)

PATIENT_COL = "patient_id"
LABEL_COL = "label"

SEEDS = [42, ]
#SEEDS = [42, 43, 44, 45, 46]   # 本解析では5 seeds
N_BOOT = 2000
RANDOM_STATE = 12345


# ============================================================
# Load
# ============================================================
df = pd.read_csv(OOF_PATH)

pred_cols = [f"oof_seed{s}" for s in SEEDS]

missing = [c for c in pred_cols if c not in df.columns]
if missing:
    raise ValueError(
        f"Missing prediction columns: {missing}\n"
        "まだ1 seedしか実行していない場合は SEEDS=[42] にしてください。"
    )

print("Images:", len(df))
print("Patients:", df[PATIENT_COL].nunique())


# ============================================================
# 1. Patient-level aggregation
#    複数画像を持つ患者では予測確率を平均
# ============================================================
# 患者内でlabelが一貫しているか確認
label_check = df.groupby(PATIENT_COL)[LABEL_COL].nunique()

if (label_check > 1).any():
    bad_ids = label_check[label_check > 1].index.tolist()
    raise ValueError(
        f"同一患者内でlabelが不一致です: {bad_ids[:10]}"
    )

agg_dict = {
    LABEL_COL: "first",
}

for col in pred_cols:
    agg_dict[col] = "mean"

patient_df = (
    df.groupby(PATIENT_COL, as_index=False)
      .agg(agg_dict)
)

print("\nPatient-level dataset")
print(patient_df.shape)
print(patient_df[LABEL_COL].value_counts())


# ============================================================
# 2. Seedごとの patient-level OOF AUROC
# ============================================================
seed_results = []

y = patient_df[LABEL_COL].astype(int).to_numpy()

for seed in SEEDS:
    col = f"oof_seed{seed}"
    pred = patient_df[col].to_numpy()

    auc = roc_auc_score(y, pred)

    seed_results.append({
        "seed": seed,
        "patient_level_auc": auc
    })

seed_results = pd.DataFrame(seed_results)

mean_auc = seed_results["patient_level_auc"].mean()

# sample SD
sd_auc = seed_results["patient_level_auc"].std(ddof=1) if len(SEEDS) > 1 else np.nan


# ============================================================
# 3. Primary prediction
#    5 seedsのpatient-level OOF予測を平均
# ============================================================
patient_df["oof_mean_seeds"] = patient_df[pred_cols].mean(axis=1)

primary_pred = patient_df["oof_mean_seeds"].to_numpy()

primary_auc = roc_auc_score(y, primary_pred)


# ============================================================
# 4. Patient-level stratified bootstrap
#
#    患者単位でresampling。
#    Female / Maleをそれぞれ復元抽出してclass balanceを保持。
# ============================================================
def bootstrap_auc_patient_level(
    y_true,
    y_pred,
    n_boot=5000,
    random_state=12345
):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)

    rng = np.random.default_rng(random_state)

    idx0 = np.where(y_true == 0)[0]
    idx1 = np.where(y_true == 1)[0]

    boot_aucs = []

    for _ in range(n_boot):

        # classごとにpatientを復元抽出
        boot0 = rng.choice(
            idx0,
            size=len(idx0),
            replace=True
        )

        boot1 = rng.choice(
            idx1,
            size=len(idx1),
            replace=True
        )

        boot_idx = np.concatenate([boot0, boot1])

        auc = roc_auc_score(
            y_true[boot_idx],
            y_pred[boot_idx]
        )

        boot_aucs.append(auc)

    boot_aucs = np.asarray(boot_aucs)

    ci_lower = np.percentile(boot_aucs, 2.5)
    ci_upper = np.percentile(boot_aucs, 97.5)

    return ci_lower, ci_upper, boot_aucs


ci_low, ci_high, boot_aucs = bootstrap_auc_patient_level(
    y,
    primary_pred,
    n_boot=N_BOOT,
    random_state=RANDOM_STATE
)


# ============================================================
# 5. Results
# ============================================================
print("\n==========================================")
print("PRIMARY ANALYSIS")
print("==========================================")

print(
    f"Patient-level AUROC = {primary_auc:.3f} "
    f"(95% CI {ci_low:.3f}-{ci_high:.3f})"
)

print("\n==========================================")
print("SEED-LEVEL REPRODUCIBILITY")
print("==========================================")

display(seed_results)

if len(SEEDS) > 1:
    print(
        f"5-seed AUROC mean ± SD = "
        f"{mean_auc:.3f} ± {sd_auc:.3f}"
    )
else:
    print(
        f"Seed {SEEDS[0]} AUROC = {mean_auc:.3f}"
    )


# ============================================================
# 6. Save
# ============================================================
# summary = pd.DataFrame([{
#     "n_patients": len(patient_df),
#     "primary_patient_auc": primary_auc,
#     "bootstrap_ci_lower": ci_low,
#     "bootstrap_ci_upper": ci_high,
#     "n_bootstrap": N_BOOT,
#     "seed_auc_mean": mean_auc,
#     "seed_auc_sd": sd_auc,
#     "n_seeds": len(SEEDS),
# }])

# summary.to_csv(
#     "/content/drive/MyDrive/QC/results/"
#     "patient_level_auc_summary.csv",
#     index=False
# )

# seed_results.to_csv(
#     "/content/drive/MyDrive/QC/results/"
#     "patient_level_seed_auc.csv",
#     index=False
# )

# patient_df.to_csv(
#     "/content/drive/MyDrive/QC/results/"
#     "patient_level_oof_predictions.csv",
#     index=False
# )

# print("\nSaved.")

Images: 404
Patients: 296

Patient-level dataset
(296, 3)
label
1    161
0    135
Name: count, dtype: int64

==========================================
PRIMARY ANALYSIS
==========================================
Patient-level AUROC = 0.748 (95% CI 0.691-0.803)

==========================================
SEED-LEVEL REPRODUCIBILITY
==========================================

   seed  patient_level_auc
0    42           0.748056

Seed 42 AUROC = 0.748

# 12-17

In [22]:
from pediatric_resnet_ft import build_dataset_csv

df_young = build_dataset_csv(
    metadata_path="/content/drive/MyDrive/PedAI_ChestXp/For_finetuning/QC/merged_reviewer_results_260906.xlsx",
    image_dir="/content/drive/MyDrive/PedAI_ChestXp/For_finetuning/QC/age_12_17",
    output_csv="/content/drive/MyDrive/QC/age_12_17.csv",
)

print(df_young.shape)
display(df_young.head())

print("\nImages:", len(df_young))
print("Patients:", df_young["patient_id"].nunique())
print("\nSex:")
print(df_young["label"].value_counts())

(565, 6)

,patient_id,image_name,path,label,age,age_group
0,911,00000911_001.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,1,16,age_12_17
1,911,00000911_003.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,1,16,age_12_17
2,960,00000960_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,0,16,age_12_17
3,1054,00001054_000.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,1,12,age_12_17
4,1054,00001054_002.png,/content/drive/.shortcut-targets-by-id/18RK_Lq...,1,13,age_12_17

Images: 565
Patients: 408

Sex:
label
1    319
0    246
Name: count, dtype: int64

In [23]:
from pediatric_resnet_ft import run_cv

results = run_cv(
    csv_path="/content/drive/MyDrive/QC/age_12_17.csv",

    pretrained="adult",
    pretrained_path="/content/drive/MyDrive/colab_最小データセット/models/Morimoto_Adult_AgeFixed_20260923_共有用/resnet50_pa_adult_agefixed_morimoto_20260923_weights.pt",

    mode="layer4",

    seeds=[42],
    n_splits=5,

    epochs=30,
    batch_size=16,

    id_col="patient_id",

    output_dir="/content/drive/MyDrive/QC/results/test_adolescent_layer4",)

Device: cuda (Tesla T4)
CV: 1 seed(s) x 5 folds = 5 models

Seed 1/1 (seed=42)
  Fold 1/5 | train=461 valid=104
    Epoch 01/30 | train loss=0.3310 AUC=0.9723 | val loss=0.4691 AUC=0.9192
    Epoch 02/30 | train loss=0.1750 AUC=0.9865 | val loss=0.4099 AUC=0.9238
    Epoch 03/30 | train loss=0.1759 AUC=0.9848 | val loss=0.3935 AUC=0.9245
    Epoch 04/30 | train loss=0.1169 AUC=0.9913 | val loss=0.3971 AUC=0.9230
    Epoch 05/30 | train loss=0.0834 AUC=0.9962 | val loss=0.4085 AUC=0.9192
    Epoch 06/30 | train loss=0.0535 AUC=0.9982 | val loss=0.4267 AUC=0.9146
    Epoch 07/30 | train loss=0.0541 AUC=0.9988 | val loss=0.4449 AUC=0.9154
    Epoch 08/30 | train loss=0.0271 AUC=0.9997 | val loss=0.4787 AUC=0.9138
    Epoch 09/30 | train loss=0.0204 AUC=0.9999 | val loss=0.5168 AUC=0.9074
    Epoch 10/30 | train loss=0.0211 AUC=0.9999 | val loss=0.5461 AUC=0.9051
    Epoch 11/30 | train loss=0.0220 AUC=0.9998 | val loss=0.5768 AUC=0.9074
    Epoch 12/30 | train loss=0.0135 AUC=0.9999 | val loss=0.6086 AUC=0.9032
    Epoch 13/30 | train loss=0.0108 AUC=1.0000 | val loss=0.6177 AUC=0.9009
    Epoch 14/30 | train loss=0.0085 AUC=1.0000 | val loss=0.6241 AUC=0.9013
    Epoch 15/30 | train loss=0.0034 AUC=1.0000 | val loss=0.6420 AUC=0.9020
    Epoch 16/30 | train loss=0.0041 AUC=1.0000 | val loss=0.6584 AUC=0.9009
    Epoch 17/30 | train loss=0.0069 AUC=1.0000 | val loss=0.6661 AUC=0.8933
    Epoch 18/30 | train loss=0.0044 AUC=1.0000 | val loss=0.6905 AUC=0.8952
    Epoch 19/30 | train loss=0.0022 AUC=1.0000 | val loss=0.6992 AUC=0.8967
    Epoch 20/30 | train loss=0.0015 AUC=1.0000 | val loss=0.6924 AUC=0.8971
    Epoch 21/30 | train loss=0.0018 AUC=1.0000 | val loss=0.7015 AUC=0.8963
    Epoch 22/30 | train loss=0.0048 AUC=1.0000 | val loss=0.7075 AUC=0.8974
    Epoch 23/30 | train loss=0.0018 AUC=1.0000 | val loss=0.7089 AUC=0.8963
    Epoch 24/30 | train loss=0.0015 AUC=1.0000 | val loss=0.7168 AUC=0.8963
    Epoch 25/30 | train loss=0.0016 AUC=1.0000 | val loss=0.7151 AUC=0.8982
    Epoch 26/30 | train loss=0.0031 AUC=1.0000 | val loss=0.7242 AUC=0.8974
    Epoch 27/30 | train loss=0.0016 AUC=1.0000 | val loss=0.7239 AUC=0.8971
    Epoch 28/30 | train loss=0.0025 AUC=1.0000 | val loss=0.7416 AUC=0.8952
    Epoch 29/30 | train loss=0.0015 AUC=1.0000 | val loss=0.7330 AUC=0.8974
    Epoch 30/30 | train loss=0.0023 AUC=1.0000 | val loss=0.7339 AUC=0.8971
  Fold 1/5 finished | best AUC=0.9245
  Fold 2/5 | train=456 valid=109
    Epoch 01/30 | train loss=0.4121 AUC=0.9627 | val loss=0.2658 AUC=0.9771
    Epoch 02/30 | train loss=0.2843 AUC=0.9695 | val loss=0.2243 AUC=0.9758
    Epoch 03/30 | train loss=0.1540 AUC=0.9876 | val loss=0.2233 AUC=0.9751
    Epoch 04/30 | train loss=0.1338 AUC=0.9894 | val loss=0.2101 AUC=0.9747
    Epoch 05/30 | train loss=0.1035 AUC=0.9941 | val loss=0.2113 AUC=0.9734
    Epoch 06/30 | train loss=0.0840 AUC=0.9963 | val loss=0.2048 AUC=0.9727
    Epoch 07/30 | train loss=0.0661 AUC=0.9981 | val loss=0.2159 AUC=0.9737
    Epoch 08/30 | train loss=0.0569 AUC=0.9984 | val loss=0.2292 AUC=0.9734
    Epoch 09/30 | train loss=0.0389 AUC=0.9994 | val loss=0.2112 AUC=0.9727
    Epoch 10/30 | train loss=0.0338 AUC=0.9993 | val loss=0.2275 AUC=0.9730
    Epoch 11/30 | train loss=0.0202 AUC=0.9999 | val loss=0.2255 AUC=0.9723
    Epoch 12/30 | train loss=0.0132 AUC=1.0000 | val loss=0.2376 AUC=0.9727
    Epoch 13/30 | train loss=0.0058 AUC=1.0000 | val loss=0.2400 AUC=0.9740
    Epoch 14/30 | train loss=0.0241 AUC=0.9996 | val loss=0.2180 AUC=0.9754
    Epoch 15/30 | train loss=0.0115 AUC=1.0000 | val loss=0.2493 AUC=0.9737
    Epoch 16/30 | train loss=0.0115 AUC=1.0000 | val loss=0.2430 AUC=0.9751
    Epoch 17/30 | train loss=0.0054 AUC=1.0000 | val loss=0.2490 AUC=0.9730
    Epoch 18/30 | train loss=0.0047 AUC=1.0000 | val loss=0.2499 AUC=0.9727
    Epoch 19/30 | train loss=0.0041 AUC=1.0000 | val loss=0.2491 AUC=0.9720
    Epoch 20/30 | train loss=0.0040 AUC=1.0000 | val loss=0.2543 AUC=0.9727
    Epoch 21/30 | train loss=0.0026 AUC=1.0000 | val loss=0.2499 AUC=0.9730
    Epoch 22/30 | train loss=0.0055 AUC=1.0000 | val loss=0.2480 AUC=0.9730
    Epoch 23/30 | train loss=0.0019 AUC=1.0000 | val loss=0.2616 AUC=0.9720
    Epoch 24/30 | train loss=0.0024 AUC=1.0000 | val loss=0.2586 AUC=0.9730
    Epoch 25/30 | train loss=0.0017 AUC=1.0000 | val loss=0.2560 AUC=0.9723
    Epoch 26/30 | train loss=0.0035 AUC=1.0000 | val loss=0.2601 AUC=0.9710
    Epoch 27/30 | train loss=0.0025 AUC=1.0000 | val loss=0.2577 AUC=0.9710
    Epoch 28/30 | train loss=0.0027 AUC=1.0000 | val loss=0.2619 AUC=0.9720
    Epoch 29/30 | train loss=0.0030 AUC=1.0000 | val loss=0.2652 AUC=0.9720
    Epoch 30/30 | train loss=0.0026 AUC=1.0000 | val loss=0.2601 AUC=0.9710
  Fold 2/5 finished | best AUC=0.9771
  Fold 3/5 | train=447 valid=118
    Epoch 01/30 | train loss=0.4951 AUC=0.9555 | val loss=0.2248 AUC=0.9771
    Epoch 02/30 | train loss=0.2330 AUC=0.9777 | val loss=0.1949 AUC=0.9797
    Epoch 03/30 | train loss=0.2039 AUC=0.9787 | val loss=0.1718 AUC=0.9823
    Epoch 04/30 | train loss=0.1699 AUC=0.9815 | val loss=0.1682 AUC=0.9850
    Epoch 05/30 | train loss=0.1421 AUC=0.9887 | val loss=0.1699 AUC=0.9838
    Epoch 06/30 | train loss=0.1034 AUC=0.9946 | val loss=0.1709 AUC=0.9850
    Epoch 07/30 | train loss=0.0800 AUC=0.9964 | val loss=0.1698 AUC=0.9826
    Epoch 08/30 | train loss=0.0649 AUC=0.9982 | val loss=0.1860 AUC=0.9786
    Epoch 09/30 | train loss=0.0353 AUC=0.9999 | val loss=0.1960 AUC=0.9766
    Epoch 10/30 | train loss=0.0195 AUC=1.0000 | val loss=0.2109 AUC=0.9737
    Epoch 11/30 | train loss=0.0192 AUC=1.0000 | val loss=0.2111 AUC=0.9745
    Epoch 12/30 | train loss=0.0148 AUC=1.0000 | val loss=0.2235 AUC=0.9728
    Epoch 13/30 | train loss=0.0095 AUC=1.0000 | val loss=0.2228 AUC=0.9742
    Epoch 14/30 | train loss=0.0065 AUC=1.0000 | val loss=0.2167 AUC=0.9754
    Epoch 15/30 | train loss=0.0040 AUC=1.0000 | val loss=0.2267 AUC=0.9737
    Epoch 16/30 | train loss=0.0071 AUC=1.0000 | val loss=0.2458 AUC=0.9725
    Epoch 17/30 | train loss=0.0064 AUC=1.0000 | val loss=0.2404 AUC=0.9722
    Epoch 18/30 | train loss=0.0056 AUC=1.0000 | val loss=0.2359 AUC=0.9740
    Epoch 19/30 | train loss=0.0030 AUC=1.0000 | val loss=0.2461 AUC=0.9708
    Epoch 20/30 | train loss=0.0024 AUC=1.0000 | val loss=0.2444 AUC=0.9734
    Epoch 21/30 | train loss=0.0023 AUC=1.0000 | val loss=0.2453 AUC=0.9742
    Epoch 22/30 | train loss=0.0022 AUC=1.0000 | val loss=0.2488 AUC=0.9734
    Epoch 23/30 | train loss=0.0026 AUC=1.0000 | val loss=0.2537 AUC=0.9719
    Epoch 24/30 | train loss=0.0026 AUC=1.0000 | val loss=0.2534 AUC=0.9722
    Epoch 25/30 | train loss=0.0039 AUC=1.0000 | val loss=0.2540 AUC=0.9719
    Epoch 26/30 | train loss=0.0057 AUC=1.0000 | val loss=0.2547 AUC=0.9714
    Epoch 27/30 | train loss=0.0024 AUC=1.0000 | val loss=0.2591 AUC=0.9711
    Epoch 28/30 | train loss=0.0018 AUC=1.0000 | val loss=0.2545 AUC=0.9714
    Epoch 29/30 | train loss=0.0018 AUC=1.0000 | val loss=0.2581 AUC=0.9693
    Epoch 30/30 | train loss=0.0039 AUC=1.0000 | val loss=0.2537 AUC=0.9719
  Fold 3/5 finished | best AUC=0.9850
  Fold 4/5 | train=450 valid=115
    Epoch 01/30 | train loss=0.4681 AUC=0.9591 | val loss=0.1884 AUC=0.9873
    Epoch 02/30 | train loss=0.2732 AUC=0.9721 | val loss=0.1566 AUC=0.9873
    Epoch 03/30 | train loss=0.1717 AUC=0.9825 | val loss=0.1348 AUC=0.9908
    Epoch 04/30 | train loss=0.1876 AUC=0.9827 | val loss=0.1274 AUC=0.9917
    Epoch 05/30 | train loss=0.1389 AUC=0.9891 | val loss=0.1340 AUC=0.9892
    Epoch 06/30 | train loss=0.1124 AUC=0.9924 | val loss=0.1252 AUC=0.9898
    Epoch 07/30 | train loss=0.0798 AUC=0.9973 | val loss=0.1237 AUC=0.9905
    Epoch 08/30 | train loss=0.0662 AUC=0.9982 | val loss=0.1329 AUC=0.9886
    Epoch 09/30 | train loss=0.0614 AUC=0.9976 | val loss=0.1245 AUC=0.9911
    Epoch 10/30 | train loss=0.0496 AUC=0.9996 | val loss=0.1447 AUC=0.9863
    Epoch 11/30 | train loss=0.0377 AUC=0.9997 | val loss=0.1144 AUC=0.9921
    Epoch 12/30 | train loss=0.0184 AUC=1.0000 | val loss=0.1215 AUC=0.9921
    Epoch 13/30 | train loss=0.0217 AUC=0.9999 | val loss=0.1011 AUC=0.9933
    Epoch 14/30 | train loss=0.0149 AUC=1.0000 | val loss=0.1523 AUC=0.9914
    Epoch 15/30 | train loss=0.0082 AUC=1.0000 | val loss=0.1138 AUC=0.9927
    Epoch 16/30 | train loss=0.0084 AUC=1.0000 | val loss=0.1174 AUC=0.9937
    Epoch 17/30 | train loss=0.0145 AUC=1.0000 | val loss=0.1604 AUC=0.9841
    Epoch 18/30 | train loss=0.0107 AUC=1.0000 | val loss=0.1251 AUC=0.9892
    Epoch 19/30 | train loss=0.0098 AUC=1.0000 | val loss=0.1143 AUC=0.9924
    Epoch 20/30 | train loss=0.0105 AUC=1.0000 | val loss=0.1041 AUC=0.9933
    Epoch 21/30 | train loss=0.0077 AUC=1.0000 | val loss=0.1199 AUC=0.9908
    Epoch 22/30 | train loss=0.0080 AUC=1.0000 | val loss=0.1305 AUC=0.9892
    Epoch 23/30 | train loss=0.0045 AUC=1.0000 | val loss=0.1268 AUC=0.9911
    Epoch 24/30 | train loss=0.0050 AUC=1.0000 | val loss=0.1240 AUC=0.9898
    Epoch 25/30 | train loss=0.0065 AUC=1.0000 | val loss=0.1110 AUC=0.9917
    Epoch 26/30 | train loss=0.0049 AUC=1.0000 | val loss=0.1177 AUC=0.9914
    Epoch 27/30 | train loss=0.0060 AUC=1.0000 | val loss=0.0991 AUC=0.9937
    Epoch 28/30 | train loss=0.0055 AUC=1.0000 | val loss=0.1126 AUC=0.9927
    Epoch 29/30 | train loss=0.0043 AUC=1.0000 | val loss=0.1479 AUC=0.9889
    Epoch 30/30 | train loss=0.0064 AUC=1.0000 | val loss=0.1240 AUC=0.9902
  Fold 4/5 finished | best AUC=0.9937
  Fold 5/5 | train=446 valid=119
    Epoch 01/30 | train loss=0.3931 AUC=0.9659 | val loss=0.4780 AUC=0.9702
    Epoch 02/30 | train loss=0.2308 AUC=0.9738 | val loss=0.4038 AUC=0.9694
    Epoch 03/30 | train loss=0.1467 AUC=0.9861 | val loss=0.3783 AUC=0.9671
    Epoch 04/30 | train loss=0.1578 AUC=0.9843 | val loss=0.3780 AUC=0.9671
    Epoch 05/30 | train loss=0.1159 AUC=0.9914 | val loss=0.3650 AUC=0.9654
    Epoch 06/30 | train loss=0.0736 AUC=0.9976 | val loss=0.3979 AUC=0.9643
    Epoch 07/30 | train loss=0.0522 AUC=0.9994 | val loss=0.4207 AUC=0.9612
    Epoch 08/30 | train loss=0.0346 AUC=0.9999 | val loss=0.4306 AUC=0.9586
    Epoch 09/30 | train loss=0.0221 AUC=1.0000 | val loss=0.4751 AUC=0.9595
    Epoch 10/30 | train loss=0.0356 AUC=0.9994 | val loss=0.4959 AUC=0.9538
    Epoch 11/30 | train loss=0.0201 AUC=0.9999 | val loss=0.5031 AUC=0.9566
    Epoch 12/30 | train loss=0.0108 AUC=1.0000 | val loss=0.4850 AUC=0.9561
    Epoch 13/30 | train loss=0.0119 AUC=1.0000 | val loss=0.5433 AUC=0.9535
    Epoch 14/30 | train loss=0.0115 AUC=1.0000 | val loss=0.5145 AUC=0.9521
    Epoch 15/30 | train loss=0.0288 AUC=0.9982 | val loss=0.5253 AUC=0.9541
    Epoch 16/30 | train loss=0.0036 AUC=1.0000 | val loss=0.5065 AUC=0.9532
    Epoch 17/30 | train loss=0.0046 AUC=1.0000 | val loss=0.4945 AUC=0.9535
    Epoch 18/30 | train loss=0.0044 AUC=1.0000 | val loss=0.4948 AUC=0.9544
    Epoch 19/30 | train loss=0.0036 AUC=1.0000 | val loss=0.5039 AUC=0.9527
    Epoch 20/30 | train loss=0.0083 AUC=1.0000 | val loss=0.5185 AUC=0.9527
    Epoch 21/30 | train loss=0.0035 AUC=1.0000 | val loss=0.5245 AUC=0.9518
    Epoch 22/30 | train loss=0.0057 AUC=1.0000 | val loss=0.5036 AUC=0.9529
    Epoch 23/30 | train loss=0.0023 AUC=1.0000 | val loss=0.4934 AUC=0.9527
    Epoch 24/30 | train loss=0.0029 AUC=1.0000 | val loss=0.4981 AUC=0.9532
    Epoch 25/30 | train loss=0.0046 AUC=1.0000 | val loss=0.5151 AUC=0.9541
    Epoch 26/30 | train loss=0.0028 AUC=1.0000 | val loss=0.5060 AUC=0.9552
    Epoch 27/30 | train loss=0.0021 AUC=1.0000 | val loss=0.5038 AUC=0.9549
    Epoch 28/30 | train loss=0.0022 AUC=1.0000 | val loss=0.4968 AUC=0.9544
    Epoch 29/30 | train loss=0.0020 AUC=1.0000 | val loss=0.5084 AUC=0.9549
    Epoch 30/30 | train loss=0.0038 AUC=1.0000 | val loss=0.4951 AUC=0.9538
  Fold 5/5 finished | best AUC=0.9702
Seed 42 OOF AUC = 0.9717

Finished. Mean-prediction OOF AUC = 0.9717
Saved to: /content/drive/MyDrive/QC/results/test_adolescent_layer4

In [24]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

# ============================================================
# Settings
# ============================================================
OOF_PATH = (
    "/content/drive/MyDrive/QC/results/"
    "test_adolescent_layer4/oof_predictions.csv"
)

PATIENT_COL = "patient_id"
LABEL_COL = "label"

SEEDS = [42, ]
#SEEDS = [42, 43, 44, 45, 46]   # 本解析では5 seeds
N_BOOT = 2000
RANDOM_STATE = 12345


# ============================================================
# Load
# ============================================================
df = pd.read_csv(OOF_PATH)

pred_cols = [f"oof_seed{s}" for s in SEEDS]

missing = [c for c in pred_cols if c not in df.columns]
if missing:
    raise ValueError(
        f"Missing prediction columns: {missing}\n"
        "まだ1 seedしか実行していない場合は SEEDS=[42] にしてください。"
    )

print("Images:", len(df))
print("Patients:", df[PATIENT_COL].nunique())


# ============================================================
# 1. Patient-level aggregation
#    複数画像を持つ患者では予測確率を平均
# ============================================================
# 患者内でlabelが一貫しているか確認
label_check = df.groupby(PATIENT_COL)[LABEL_COL].nunique()

if (label_check > 1).any():
    bad_ids = label_check[label_check > 1].index.tolist()
    raise ValueError(
        f"同一患者内でlabelが不一致です: {bad_ids[:10]}"
    )

agg_dict = {
    LABEL_COL: "first",
}

for col in pred_cols:
    agg_dict[col] = "mean"

patient_df = (
    df.groupby(PATIENT_COL, as_index=False)
      .agg(agg_dict)
)

print("\nPatient-level dataset")
print(patient_df.shape)
print(patient_df[LABEL_COL].value_counts())


# ============================================================
# 2. Seedごとの patient-level OOF AUROC
# ============================================================
seed_results = []

y = patient_df[LABEL_COL].astype(int).to_numpy()

for seed in SEEDS:
    col = f"oof_seed{seed}"
    pred = patient_df[col].to_numpy()

    auc = roc_auc_score(y, pred)

    seed_results.append({
        "seed": seed,
        "patient_level_auc": auc
    })

seed_results = pd.DataFrame(seed_results)

mean_auc = seed_results["patient_level_auc"].mean()

# sample SD
sd_auc = seed_results["patient_level_auc"].std(ddof=1) if len(SEEDS) > 1 else np.nan


# ============================================================
# 3. Primary prediction
#    5 seedsのpatient-level OOF予測を平均
# ============================================================
patient_df["oof_mean_seeds"] = patient_df[pred_cols].mean(axis=1)

primary_pred = patient_df["oof_mean_seeds"].to_numpy()

primary_auc = roc_auc_score(y, primary_pred)


# ============================================================
# 4. Patient-level stratified bootstrap
#
#    患者単位でresampling。
#    Female / Maleをそれぞれ復元抽出してclass balanceを保持。
# ============================================================
def bootstrap_auc_patient_level(
    y_true,
    y_pred,
    n_boot=5000,
    random_state=12345
):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)

    rng = np.random.default_rng(random_state)

    idx0 = np.where(y_true == 0)[0]
    idx1 = np.where(y_true == 1)[0]

    boot_aucs = []

    for _ in range(n_boot):

        # classごとにpatientを復元抽出
        boot0 = rng.choice(
            idx0,
            size=len(idx0),
            replace=True
        )

        boot1 = rng.choice(
            idx1,
            size=len(idx1),
            replace=True
        )

        boot_idx = np.concatenate([boot0, boot1])

        auc = roc_auc_score(
            y_true[boot_idx],
            y_pred[boot_idx]
        )

        boot_aucs.append(auc)

    boot_aucs = np.asarray(boot_aucs)

    ci_lower = np.percentile(boot_aucs, 2.5)
    ci_upper = np.percentile(boot_aucs, 97.5)

    return ci_lower, ci_upper, boot_aucs


ci_low, ci_high, boot_aucs = bootstrap_auc_patient_level(
    y,
    primary_pred,
    n_boot=N_BOOT,
    random_state=RANDOM_STATE
)


# ============================================================
# 5. Results
# ============================================================
print("\n==========================================")
print("PRIMARY ANALYSIS")
print("==========================================")

print(
    f"Patient-level AUROC = {primary_auc:.3f} "
    f"(95% CI {ci_low:.3f}-{ci_high:.3f})"
)

print("\n==========================================")
print("SEED-LEVEL REPRODUCIBILITY")
print("==========================================")

display(seed_results)

if len(SEEDS) > 1:
    print(
        f"5-seed AUROC mean ± SD = "
        f"{mean_auc:.3f} ± {sd_auc:.3f}"
    )
else:
    print(
        f"Seed {SEEDS[0]} AUROC = {mean_auc:.3f}"
    )


# ============================================================
# 6. Save
# ============================================================
# summary = pd.DataFrame([{
#     "n_patients": len(patient_df),
#     "primary_patient_auc": primary_auc,
#     "bootstrap_ci_lower": ci_low,
#     "bootstrap_ci_upper": ci_high,
#     "n_bootstrap": N_BOOT,
#     "seed_auc_mean": mean_auc,
#     "seed_auc_sd": sd_auc,
#     "n_seeds": len(SEEDS),
# }])

# summary.to_csv(
#     "/content/drive/MyDrive/QC/results/"
#     "patient_level_auc_summary.csv",
#     index=False
# )

# seed_results.to_csv(
#     "/content/drive/MyDrive/QC/results/"
#     "patient_level_seed_auc.csv",
#     index=False
# )

# patient_df.to_csv(
#     "/content/drive/MyDrive/QC/results/"
#     "patient_level_oof_predictions.csv",
#     index=False
# )

# print("\nSaved.")

Images: 565
Patients: 408

Patient-level dataset
(408, 3)
label
1    239
0    169
Name: count, dtype: int64

==========================================
PRIMARY ANALYSIS
==========================================
Patient-level AUROC = 0.970 (95% CI 0.954-0.984)

==========================================
SEED-LEVEL REPRODUCIBILITY
==========================================

   seed  patient_level_auc
0    42            0.96982

Seed 42 AUROC = 0.970